Feature/461 semester progress android widget
ApplETS/Notre-Dame pull request #1051
Opened 2024-09-07 21:28 UTC by DylanApardian

### ⁉️ Related Issue
#461 

## 📖 Description
This PR introduces the semester progress home screen widget for android.
The widget behaves the same way as in the application.
The widget is re-sizable and displays a circular progress bar when the widget is small enough.
To change the theme/language, you can hold on the widget and then:

- Drag the widget to the "Widget Settings" section (top right)

**OR** 

- Click on the the pencil icon

*See the screen recording if needed.*

### 🧪 How Has This Been Tested?
Manual testing and day to day use.

### ☑️ Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] If needed, I added analytics.
- [x] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 

### 🖼️ Screenshots (if useful):

[Screen_recording_20240907_170201.webm](https://github.com/user-attachments/assets/56b95414-9e5a-4448-a73e-c00025d7691c)

2024-09-07 21:33 UTC, XavierPaquet-Rapold commented
Est-ce que c'est possible d'utiliser les settings de l'application ou au minimum les settings du téléphone au lieu d'avoir des settings pour le widget ?

2024-09-07 21:37 UTC, DylanApardian commented
> Est-ce que c'est possible d'utiliser les settings de l'application ou au minimum les settings du téléphone au lieu d'avoir des settings pour le widget ?
@XavierPaquet-Rapold 

J'imagine que oui. Je vais tenter de faire ça ce weekend.

2024-09-15 21:08 UTC, XavierPaquet-Rapold requested changes

2024-09-15 22:17 UTC, DylanApardian commented on android/app/src/main/res/values/strings.xml
> +</resources>
C'est fait. Maintenant les strings sont en fonction de la langue du device. Si tu veut que la langue des string soit en fonction de la langue de d'appli, il va falloir des petites modif pour spécifier la locale.
Je pense pour la grande majorité des gens, leur device et appli sont set à la même langue.

2024-09-21 02:55 UTC, XavierPaquet-Rapold requested changes

2024-09-21 03:12 UTC, XavierPaquet-Rapold commented
Also, when not connected, the default text should be N/A, for now it's null on the x% progress. Also, the language should follow the app language, just like the theme. The text `x days elapsed / x days` overflows when the widget takes half the screen. Finally, when the settings change and when changing the position of the widget, the widget becomes unresponsive

2024-10-04 17:17 UTC, LouisPhilippeHeon commented
J'ai pas encore pris le temps de regarder le code, mais je l'ai testé. Pour le i18n comment ça se passe? Mon cell est en anglais mais l'app en français, le widget s'affiche en anglais. Est ce que on ne voudrait pas plutot utiliser la langue de l'app. Aussi, le changement entre light mode et dark mode est pas super smooth.

2024-10-04 22:44 UTC, DylanApardian commented
> J'ai pas encore pris le temps de regarder le code, mais je l'ai testé. Pour le i18n comment ça se passe? Mon cell est en anglais mais l'app en français, le widget s'affiche en anglais. Est ce que on ne voudrait pas plutot utiliser la langue de l'app. Aussi, le changement entre light mode et dark mode est pas super smooth.

@LouisPhilippeHeon 

- Pour la langue, c'est la langue de l'application qui est utilisée. 
- Pour le theme, il est seulement mit a jour lorsque le widget est mis a jour (chaque 30 min ou par un click sur le widget). J'imagine que c'est possible de faire un update lorsqu'on le change dans flutter. Peut-être avec des flutter method channels?

2025-02-04 02:51 UTC, closed without merging