Bugfix/1026 Android back gesture should follow navigation history
ApplETS/Notre-Dame pull request #1056
Opened 2024-09-22 20:10 UTC by BenjaminBelanger

### ⁉️ Related Issue

Closes: #1026

## 📖 Description

This PR addresses the navigation issue on Android where the **back button** and **back gesture** navigation were not functioning as expected. Previously, these actions would always return the user to the dashboard, regardless of the navigation history. This fix ensures that user is returned to the previous screen in their navigation stack. The back button should always take you back to the screen you were just on. 

Also, the change in the code ensures that the navigation history does not keep duplicate routes. This means that if a user spams two tabs repeatedly, he will not need to click the back button multiple times to go back to previous routes (check 2nd video below).

This navigation behaviour appears to be present in most Android apps.

### 🧪 How Has This Been Tested?

- Navigate to **Schedule** tab and then to the **Student** tab. When I do a back gesture or press the back button, I should be redirected to the **Schedule** tab (instead of the **Dashboard**)
- Tested in both vertical and horizontal phone orientation

### ☑️ Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] If needed, I added analytics.
- [x] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 

### 🖼️ Screenshots (if useful):

### Back button navigation demo:

https://github.com/user-attachments/assets/77bac131-a7de-497a-80da-fffe94fa3621

### Navigation when user clicks same tabs multiple times:

https://github.com/user-attachments/assets/ccc88a39-7d64-49c5-b4ce-8031118ff56e

### Navigation with back gesture:

https://github.com/user-attachments/assets/a16eee50-df4d-4ed5-aa21-381bea2c12f4

2024-09-24 01:13 UTC, LouisPhilippeHeon requested changes
Est-ce que ce serait possible d'ajouter des cas de tests pour navigation_service.dart? À part de ça, tout me semble beau.

2024-09-24 03:30 UTC, BenjaminBelanger commented
> Est-ce que ce serait possible d'ajouter des cas de tests pour navigation_service.dart? À part de ça, tout me semble beau.

Bonne idée, ça ne devrait pas être trop compliqué à intégrer. Je devrais pouvoir checker ça mercredi.

2024-09-25 19:22 UTC, EffBureau commented on lib/features/app/navigation/navigation_history_observer.dart
> +  /// Gets a clone of the navigation history as an immutable list.
J'enlèverais ces commentaires là. Généralement les commentaires servent à clarifier le code (sauf dans le cas de javadoc). Donc, si en lisant le code je peux facilement en deviner le fonctionnement, c'est un peu inutile de le "traduire en français"

Exemple: 
`
// Ce code envoie un gâteau au chocolat si c'est le jour de fête du user.

if (user.isBirthday() == true) { sendToUser(user, new Cake(Chocolate)); }
`

Le code parle pour lui même, j'ai pas besoin de l'avoir traduis dans un commentaire pour que tu le comprennes.

Un cas où les commentaires sont utiles c'est si tu dois passer par 4 chemins pour faire qqchose et que c'est la seule façon de le faire mais on ne peut pas déduire pourquoi tu le fais ou même qu'est-ce que tu fais.

Tu as surement juste vu ce genre de commentaires dans le code existant et tu as juste fais la mm chose, mais tant qu'à moi, si j'avais à modifier du code avec des commentaires dans le mm genre, je les enlèverais en mm temps.

C'est pas la fin du monde si tu les laisses là non plus. 😁

2024-10-27 01:08 UTC, XavierPaquet-Rapold approved these changes

2024-10-30 16:35 UTC, LouisPhilippeHeon approved these changes
Testé aussi sur ios, pas d'impact sur la navigation

2024-10-30 21:51 UTC, merged