Need help notice
ApplETS/Notre-Dame pull request #1057
Opened 2024-09-23 15:05 UTC by EffBureau

### ⁉️ Related Issue
No related issue

## 📖 Description

Add a dialog to warn users that we cannot help them gain access to their accounts.

### 🧪 How Has This Been Tested?

Manually
Added unit test to check if dialog shows up
Added unit test to check if cancel closes dialog
Added unit test to check if tap outside dialog closes it
Added unit tests to check if password assistance urls work

### ☑️ Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [N/A] If it is a core feature, I have added thorough tests.
- [x] If needed, I added analytics. // I added analytics to see if the dialog is actually useful and how many times it has been used
- [x] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 

### 🖼️ Screenshots (if useful):

![image](https://github.com/user-attachments/assets/0e65b495-71ce-4ac1-b097-ca491f5380cf)

2024-11-08 15:05 UTC, XavierPaquet-Rapold requested changes

2024-11-08 15:05 UTC, XavierPaquet-Rapold commented on test/features/more/faq/faq_viewmodel_test.dart
> +      });
Ces tests sont là pourquoi ?

2024-11-08 15:05 UTC, XavierPaquet-Rapold commented on test/features/more/faq/faq_view_test.dart
> +        await tester.pump(const Duration(milliseconds: 500));
Tu peux pas utiliser `await tester.pumpAndSettle();` au lieu de mettre une durée d'attente ?

2024-11-08 15:05 UTC, XavierPaquet-Rapold commented on test/features/more/faq/faq_view_test.dart
> +        await tester.pumpAndSettle(const Duration(milliseconds: 800));
Tu peux pas utiliser await tester.pumpAndSettle(); au lieu de mettre une durée d'attente ?

2024-11-08 15:05 UTC, XavierPaquet-Rapold commented on test/features/more/faq/faq_view_test.dart
> +        await tester.pump(const Duration(milliseconds: 500));
Tu peux pas utiliser await tester.pumpAndSettle(); au lieu de mettre une durée d'attente ?

2024-11-08 15:05 UTC, XavierPaquet-Rapold commented on test/features/more/faq/faq_view_test.dart
> +        await tester.pump(const Duration(milliseconds: 500));
Tu peux pas utiliser await tester.pumpAndSettle(); au lieu de mettre une durée d'attente ?

2024-11-08 15:05 UTC, XavierPaquet-Rapold commented on test/features/more/faq/faq_view_test.dart
> +        await tester.pumpAndSettle(const Duration(milliseconds: 800));
Tu peux pas utiliser await tester.pumpAndSettle(); sans le temps d'attente au lieu de mettre une durée d'attente ?

2024-11-08 15:05 UTC, XavierPaquet-Rapold commented on test/features/more/faq/faq_view_test.dart
> +        await tester.pump(const Duration(milliseconds: 500));
Tu peux pas utiliser await tester.pumpAndSettle(); au lieu de mettre une durée d'attente ?

2024-11-08 15:05 UTC, XavierPaquet-Rapold commented on test/features/more/faq/faq_view_test.dart
> +        await tester.pump(const Duration(milliseconds: 500));
Tu peux pas utiliser await tester.pumpAndSettle(); au lieu de mettre une durée d'attente ?

2024-11-08 15:05 UTC, XavierPaquet-Rapold commented on test/features/more/faq/faq_view_test.dart
> +        await tester.pump(const Duration(milliseconds: 500));
Tu peux pas utiliser await tester.pumpAndSettle(); au lieu de mettre une durée d'attente ?

2024-11-08 15:05 UTC, XavierPaquet-Rapold commented on test/features/more/faq/faq_view_test.dart
> +        await tester.pump(const Duration(milliseconds: 500));
Tu peux pas utiliser await tester.pumpAndSettle(); au lieu de mettre une durée d'attente ?

2024-11-08 15:05 UTC, XavierPaquet-Rapold commented on test/features/more/faq/faq_view_test.dart
> +        await tester.pumpAndSettle(const Duration(milliseconds: 800));
Tu peux pas utiliser await tester.pumpAndSettle(); au lieu de mettre une durée d'attente ?

2024-11-08 15:05 UTC, XavierPaquet-Rapold commented on test/features/more/faq/faq_view_test.dart
> +        await tester.pump(const Duration(milliseconds: 500));
Tu peux pas utiliser await tester.pumpAndSettle(); au lieu de mettre une durée d'attente ?

2024-11-08 15:05 UTC, XavierPaquet-Rapold commented on test/features/more/faq/faq_view_test.dart
> +        await tester.pump(const Duration(milliseconds: 500));
Tu peux pas utiliser await tester.pumpAndSettle(); au lieu de mettre une durée d'attente ?

2024-11-08 15:05 UTC, XavierPaquet-Rapold commented on test/features/more/faq/faq_view_test.dart
> +        await tester.pump(const Duration(milliseconds: 500));
Tu peux pas utiliser await tester.pumpAndSettle(); au lieu de mettre une durée d'attente ?

2024-11-08 15:05 UTC, XavierPaquet-Rapold commented on test/features/more/faq/faq_view_test.dart
> +        await tester.pump(const Duration(milliseconds: 500));
Tu peux pas utiliser await tester.pumpAndSettle(); au lieu de mettre une durée d'attente ?

2024-11-08 15:10 UTC, XavierPaquet-Rapold requested changes

2024-11-08 15:10 UTC, XavierPaquet-Rapold commented on lib/features/more/faq/faq_view.dart
> +            showDialog(
Crée un nouveau widget pour ça aussi

2024-11-08 15:30 UTC, EffBureau commented on test/features/more/faq/faq_viewmodel_test.dart
> +      });
Nous avertir si jamais le lien n'est plus fonctionnel. C'est un lien qui est quand mm très bien caché et donc on ne s'en rendra pas compte par nous même.

Si on a une meilleure façon de faire je peux le changer.

2024-11-08 15:31 UTC, EffBureau commented on lib/features/more/faq/faq_viewmodel.dart
> +  }
C'était plus pour l'utiliser dans la page. Mais comme on veut retirer son utilisation dans la page, je vais l'enlever.

2024-11-08 15:35 UTC, EffBureau commented on lib/features/more/faq/faq_view.dart
> +            showDialog(
En parlant avec LP il m'a dit qu'il allait travailler sur les dialogues alors c'était mieux de juste le laisser comme tel puisqu'il risquait de changer des trucs et je ne voulais pas dupliquer le travail. 

Il faut que je lui demande s'il planifie tjrs de sauter la dessus sachant qu'on veut refaire l'app au complet.

2025-01-24 19:22 UTC, XavierPaquet-Rapold requested changes

2025-01-24 19:22 UTC, XavierPaquet-Rapold commented on test/features/app/widgets/need_help_notice_dialog_test.dart
> +        await tester.pumpWidget(localizedWidget(child: const FaqView()));
```suggestion
        await tester.pumpWidget(localizedWidget(child: const NeedHelpNoticeDialog()));
```

2025-01-24 19:22 UTC, XavierPaquet-Rapold commented on test/features/app/widgets/need_help_notice_dialog_test.dart
> +        await tester.pumpWidget(localizedWidget(child: const FaqView()));
```suggestion
        await tester.pumpWidget(localizedWidget(child: const NeedHelpNoticeDialog()));
```

2025-03-07 00:20 UTC, XavierPaquet-Rapold approved these changes
LGTM :fire:

2025-03-08 02:15 UTC, LouisPhilippeHeon requested changes

2025-03-08 02:15 UTC, LouisPhilippeHeon commented on lib/ui/core/ui/need_help_notice_dialog.dart
> +    this.radius = 5.0,
border radius de 8.0

2025-03-08 02:15 UTC, LouisPhilippeHeon commented on lib/ui/core/ui/need_help_notice_dialog.dart
> +        title: Text(
shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),

2025-03-24 00:41 UTC, LouisPhilippeHeon approved these changes

2025-03-24 02:08 UTC, XavierPaquet-Rapold approved these changes

2025-03-24 02:09 UTC, merged