Feature/1070 replace auto size text
ApplETS/Notre-Dame pull request #1084
Opened 2024-11-10 23:02 UTC by NakanLuca

### ⁉️ Related Issue
Issue #1070 : remove auto_size_text
## 📖 Description

I completely removed the auto_size_text dependency from the project and replaced it's calls by 'Text'.

### 🧪 How Has This Been Tested?
I compared the front end where auto_size_text was used before and after removing it on a mobile phone and a tablet.
I saw no changes.

### ☑️ Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`.

2024-11-11 00:54 UTC, XavierPaquet-Rapold requested changes

2024-11-11 00:54 UTC, XavierPaquet-Rapold commented on pubspec.yaml
> +  pub_semver: ^2.1.4
Enlever

2024-11-11 03:46 UTC, LouisPhilippeHeon requested changes

2024-11-11 03:46 UTC, LouisPhilippeHeon commented on lib/features/schedule/widgets/schedule_calendar_tile.dart
> -            AutoSizeText(
De la manière que tu l'a fait, si le texte dépasse (par exemple, il y a un cours le samedi, donc une colonne de plus à afficher, rétrécissant leur taille), le texte va simplement déborder du widget et ne sera pas visible.

Tu peux garder le comportement d'origine avec ça :
```dart
FittedBox(
    fit: BoxFit.fitWidth,
    child: Text(
        widget.title ?? "",
        style: widget.titleStyle,
        maxLines: 3
    )
)
```

2024-11-11 03:48 UTC, LouisPhilippeHeon commented on lib/features/dashboard/dashboard_view.dart
> +                  style: Theme.of(context).primaryTextTheme.bodyMedium)
Style devrait être indenté

2024-11-24 14:50 UTC, XavierPaquet-Rapold approved these changes

2024-11-24 14:54 UTC, LouisPhilippeHeon approved these changes

2024-11-24 14:54 UTC, merged