Implement edge to edge on android
ApplETS/Notre-Dame pull request #1086
Opened 2024-11-11 04:55 UTC by LouisPhilippeHeon

### ⁉️ Related Issue
Closes #1064 
Faire en sorte que la handle au base de l'écran ait un background transparent
En paysage, ne pas afficher la barre de statut.

## 📖 Description

### 🧪 How Has This Been Tested?
Tested on android, light and dark mode, landscape and portrait.

### ☑️ Checklist before requesting a review
- [X] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] If needed, I added analytics.
- [X] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 

### 🖼️ Screenshots (if useful):
<img width="493" alt="Capture d’écran, le 2024-11-10 à 23 55 18" src="https://github.com/user-attachments/assets/da22ce2b-c5d2-4d56-ac6d-9d949ef37183">

<img width="259" alt="Capture d’écran, le 2024-11-10 à 23 51 43" src="https://github.com/user-attachments/assets/1fe84599-3e69-4eff-adfc-f046a94c1ee5">

2024-11-11 14:51 UTC, XavierPaquet-Rapold submitted a review, later dismissed

2024-11-11 18:45 UTC, XavierPaquet-Rapold requested changes

2024-11-11 18:45 UTC, XavierPaquet-Rapold commented on lib/main.dart
> +  }
Juste le mettre après le build, comme on fait dans les autres classes

2024-11-11 18:51 UTC, XavierPaquet-Rapold approved these changes

2024-11-12 03:50 UTC, EffBureau submitted a review, later dismissed
LGTM 🤓

2024-11-12 03:59 UTC, merged