Remove percent_indicator lib
ApplETS/Notre-Dame pull request #1089
Opened 2024-11-12 15:42 UTC by BenjaminBelanger

### ⁉️ Related Issue
Closes: #1075 

## 📖 Description
Replaces `percent_indicator` library that is no longer maintained with native Flutter class `CircularProgressIndicator`

percent_indicator was used for:
- Student grade circular display
- Program completion circular indicator in profile view

### 🧪 How Has This Been Tested?
- Tested on Android
- Tested that the new widgets look the same as previously
- Tested that grade-based color schemes remain the same
- Tested that animations look the same
- Tested with horizontal and vertical phone orientation

### ☑️ Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] If needed, I added analytics.
- [x] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 

### 🖼️ Screenshots (if useful):

https://github.com/user-attachments/assets/58957e8b-9db0-4d47-930a-9208703d42d8

https://github.com/user-attachments/assets/11dd6bb2-5347-440a-a416-1f08478aeab0

<img src="https://github.com/user-attachments/assets/c4c346e5-7020-40d3-be95-d46374afa190" width="300" height="600">

2024-11-12 19:02 UTC, XavierPaquet-Rapold requested changes

2024-11-12 19:02 UTC, XavierPaquet-Rapold commented on lib/features/student/grades/widgets/grade_circular_progress.dart
>        ),
Mettre ça dans un widget séparé

2024-11-12 19:02 UTC, XavierPaquet-Rapold commented on lib/features/student/profile/profile_view.dart
>  Card getProgramCompletion(ProfileViewModel model, BuildContext context) {
Créer un widget contenant cet méthode

2024-11-26 20:22 UTC, BenjaminBelanger commented on lib/features/student/grades/widgets/grade_circular_progress.dart
>        ),
J'ai créé le nouveau fichier **grade_circular_indicator.dart** bd33e5b28f532e39e8ef6a438de3c5bee6e649f4

2024-11-26 20:24 UTC, BenjaminBelanger commented on lib/features/student/profile/profile_view.dart
>  Card getProgramCompletion(ProfileViewModel model, BuildContext context) {
Je l'ai mise dans un nouveau fichier **program_completion.dart** 5327ed9dd880538ec1bf770756757d9d34ba72cd

2024-11-27 02:32 UTC, XavierPaquet-Rapold approved these changes
LGTM 🔥

2024-11-29 14:02 UTC, EffBureau approved these changes
LGTM 🤓

2024-11-29 14:02 UTC, merged