Feature/accessible offline
ApplETS/Notre-Dame pull request #111
Opened 2021-05-05 04:25 UTC by JonathanDuvalV

Closes #20 

This PR add the ability to access the app when the user doesn't have an active internet connection and was previously logged in to the app.

- Added NetworkingService that uses the Connectivity package from flutter
- When no connections are available, forces fromCacheOnly to true when possible
- Modified unit tests from repository affected by the NetworkingService
- Added new tests

2021-05-05 04:29 UTC, JonathanDuvalV commented
Just realized I haven't fixed the tests related to the view models yet. I'll fix them soon.

2021-05-05 04:42 UTC, AlexandreMarkus reviewed
Not tested yet

2021-05-05 04:42 UTC, AlexandreMarkus commented on lib/core/viewmodels/profile_viewmodel.dart
> +  Future displayNoConnectionToast() async {
Duplicate, maybe add this to Utils instead

2021-05-05 04:42 UTC, AlexandreMarkus commented on lib/core/viewmodels/schedule_viewmodel.dart
> +  Future displayNoConnectionToast() async {
Duplicate here too

2021-05-05 04:42 UTC, AlexandreMarkus commented on lib/core/viewmodels/startup_viewmodel.dart
> +import 'package:notredame/core/services/networking_service.dart';
Add to section Services

2021-05-08 17:51 UTC, JonathanDuvalV commented
> Seems good to me!
> 
> I would add the connectivity type (wifi, mobile, none) inside createGithubIssue() under `"- **Version:** ${packageInfo.version} \n"`
> 
> Like this : `"- **Connectivity:** ${...} \n"`

Done!

2021-05-08 17:54 UTC, JonathanDuvalV commented
iOS doesn't compile anymore for me. I have the same issue on master. It looks like there's a problem with a Firebase dependency 

[!] CocoaPods could not find compatible versions for pod "Firebase/Analytics":
  In snapshot (Podfile.lock):
    Firebase/Analytics (= 7.3.0)

  In Podfile:
    firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 8.0.2, which depends on
      Firebase/Analytics (= 7.11.0)

Specs satisfying the `Firebase/Analytics (= 7.3.0), Firebase/Analytics (= 7.11.0)` dependency were found, but they required a higher minimum deployment target.

2021-05-08 20:09 UTC, AlexandreMarkus commented
Testé sur Android! Est-ce que IOS aussi?

2021-05-08 20:48 UTC, JonathanDuvalV commented
> Testé sur Android! Est-ce que IOS aussi?

iOS a des problemes avec les dependencies de firebase 😅 . Je regardes ca soon!

2021-05-08 21:19 UTC, JonathanDuvalV commented
@AlexandreMarkus Also works on iOS now!

2021-05-08 23:23 UTC, camillebrulotte requested changes
Nice job jojoo ! 2 p'tits changements à te sugérer :D

2021-05-08 23:23 UTC, camillebrulotte commented on test/helpers.dart
> +import 'package:notredame/core/services/networking_service.dart';
Wrong section :D

2021-05-08 23:23 UTC, camillebrulotte commented on test/viewmodels/grades_viewmodel_test.dart
> +import '../mock/services/networking_service_mock.dart';
Wrong placeee hehe

2021-05-08 23:43 UTC, JonathanDuvalV commented
> Nice job jojoo ! 2 p'tits changements à te sugérer :D

Done 😄

2021-05-09 00:27 UTC, camillebrulotte commented
LGTM ! Mais je suis incapable de tester sur IOS puisqu'il faut debug ! ):

2021-05-09 01:54 UTC, AlexandreMarkus approved these changes

2021-05-09 02:05 UTC, camillebrulotte approved these changes

2021-05-09 02:05 UTC, merged