Feature/discovery/navbar discovery
ApplETS/Notre-Dame pull request #120
Opened 2021-05-13 14:26 UTC by camillebrulotte

Here is the discovery for the navbar.

Version in french :

https://user-images.githubusercontent.com/37625944/118139159-16642580-b3d5-11eb-828a-40086e256cec.MP4

Version in english :

https://user-images.githubusercontent.com/37625944/118139125-0d735400-b3d5-11eb-9225-889452d583c2.MOV

Feel free to say if you want me to add/refactor the informations in the discovery text :D

2021-05-13 15:03 UTC, camillebrulotte commented
Je viens de réaliser que si je me déconnectes et que je me reconnecte, le Discovery est relancer puisque la cache se fait effacer. J'imagine qu'il faudrait pas que ça fasse ça ? :)

2021-05-13 15:37 UTC, AlexandreMarkus commented
J'ai seulement regardé les vidéos mais c'est vraiment nice!!!

2021-05-13 21:56 UTC, AlexandreMarkus commented
> Je viens de réaliser que si je me déconnectes et que je me reconnecte, le Discovery est relancer puisque la cache se fait effacer. J'imagine qu'il faudrait pas que ça fasse ça ? :) 

Effectivement. Je ne sais pas si c'est possible mais en gros le but est que suite à l'installation de l'app, Discovery soit disponible

2021-05-13 22:36 UTC, camillebrulotte commented
> > Je viens de réaliser que si je me déconnectes et que je me reconnecte, le Discovery est relancer puisque la cache se fait effacer. J'imagine qu'il faudrait pas que ça fasse ça ? :)
> 
> Effectivement. Je ne sais pas si c'est possible mais en gros le but est que suite à l'installation de l'app, Discovery soit disponible

Yes live c'est ça que ça fait ! :D

2021-05-14 10:03 UTC, AlexandreMarkus commented
> > > Je viens de réaliser que si je me déconnectes et que je me reconnecte, le Discovery est relancer puisque la cache se fait effacer. J'imagine qu'il faudrait pas que ça fasse ça ? :)
> > 
> > Effectivement. Je ne sais pas si c'est possible mais en gros le but est que suite à l'installation de l'app, Discovery soit disponible
> 
> Yes live c'est ça que ça fait ! :D 

Super, il faudrait juste trouver une façon de ne pas réactiver suite à un logout

2021-05-14 13:26 UTC, apomalyn commented
@camillebrulotte c'est pas grave si le discovery se relance après un log out tant que l'on peut le skip 😄  sinon pour éviter ça faudrait modifier le logout pour qu'il clear les informations liés a l'utilisateur et non l'entiereté de la cache (userPreferencies ici). 

J'ai vu deux trois correctif a faire dans les textes mais majoritairement ça m'a l'air bon!! Juste ajouter un moyen de le skip et on est bon 😄  (si tu vois pas comment faire un truc directement dans le discovery, une popup type 'Get a tour' fera l'affaire 😄

2021-05-14 17:40 UTC, apomalyn reviewed
Premier passage 😄

2021-05-14 17:40 UTC, apomalyn commented on lib/l10n/intl_fr.arb
> +  "discovery_navbar_schedule_page_details": "La page Horaire affiche les évènements de votre calendrier scolaire.",
```suggestion
  "discovery_navbar_schedule_page_details": "Sur cette page vous pourrez trouver votre horaire ainsi que les autres événements importants.",  
```
Qu'en penses-tu?

2021-05-14 17:40 UTC, apomalyn commented on lib/l10n/intl_fr.arb
> +  "discovery_navbar_schedule_page_details_format": "Dans les paramètres, vous pouvez changer les paramètres par défaut du calendrier.",
Même chose si c'est possible de changer de bulle pour faire cliquer sur le bouton de réglages et lui faire ouvrir la page de settings?

2021-05-14 18:44 UTC, camillebrulotte commented
> @camillebrulotte c'est pas grave si le discovery se relance après un log out tant que l'on peut le skip 😄 sinon pour éviter ça faudrait modifier le logout pour qu'il clear les informations liés a l'utilisateur et non l'entiereté de la cache (userPreferencies ici).
> 
> J'ai vu deux trois correctif a faire dans les textes mais majoritairement ça m'a l'air bon!! Juste ajouter un moyen de le skip et on est bon 😄 (si tu vois pas comment faire un truc directement dans le discovery, une popup type 'Get a tour' fera l'affaire 😄

Bonne idée ! J'ai rajouter ça :
<img src="https://user-images.githubusercontent.com/37625944/118314768-961bee00-b4c2-11eb-9e20-7e5a1b020336.png"  width="400">

(Il est aussi dismissable si tu clicks en dehors du dsiscovery)

2021-05-14 18:52 UTC, camillebrulotte commented on lib/l10n/intl_fr.arb
> +  "discovery_navbar_dashboard_page_details_restore": "Pour restaurer les changements, cliquer sur l'icône en haut à droite.",
Donc je rajoute l'icone à la ligne. C'est bien ça ?

2021-05-14 18:56 UTC, camillebrulotte commented on lib/l10n/intl_fr.arb
> +  "discovery_navbar_schedule_page_details_format": "Dans les paramètres, vous pouvez changer les paramètres par défaut du calendrier.",
Hmm mais ça c'est le discovery "par page" ? Je pensais que je devais seulement faire le discovery de la navbar dans cette branche étant donné que la pr est déjà assez grande. Mais je me trompe peut-être :D

2021-05-15 14:44 UTC, camillebrulotte commented
@elornHamon Tu en dis quoi comme ça ? :D 

Finalement il fallait simplement rajouter "pulseDuration: const Duration(seconds: 5)," 


https://user-images.githubusercontent.com/37625944/118365368-77713200-b56a-11eb-8ac2-8607b09c746e.mp4

2021-05-15 14:48 UTC, elornHamon commented
> @elornHamon Tu en dis quoi comme ça ? :D
> 
> Finalement il fallait simplement rajouter "pulseDuration: const Duration(seconds: 5),"
> 
>  2021-05-15.10-43-44.mp4

C'est parfait 😄

2021-05-16 14:51 UTC, AlexandreMarkus commented on lib/core/constants/preferences_flags.dart
>    welcome,
maybe change the flag to languageChoice ?

2021-05-16 14:53 UTC, AlexandreMarkus commented
Il faudrait aussi mentionner que la page ETS inclus les mesures de sécurité (requis par l'école)

2021-05-18 21:08 UTC, apomalyn commented on lib/l10n/intl_fr.arb
> +  "discovery_navbar_schedule_page_details_format": "Dans les paramètres, vous pouvez changer les paramètres par défaut du calendrier.",
Je suis d'accord avec toi de le faire dans une autre branche :smile: 
Va falloir update les textes alors en prevision du discovery de chaque page ^^

2021-05-18 21:08 UTC, apomalyn commented on lib/l10n/intl_fr.arb
> +  "discovery_navbar_schedule_page_details_format": "Dans les paramètres, vous pouvez changer les paramètres par défaut du calendrier.",
Je suis d'accord avec toi de le faire dans une autre branche :smile: 
Va falloir update les textes alors en prevision du discovery de chaque page ^^

2021-05-18 21:42 UTC, camillebrulotte commented on lib/l10n/intl_fr.arb
> +  "discovery_navbar_schedule_page_details_format": "Dans les paramètres, vous pouvez changer les paramètres par défaut du calendrier.",
Parfait je le rajoute au projet ! :D

2021-05-20 15:10 UTC, apomalyn requested changes
Two minor changes and that will be good for me 😄

2021-05-20 15:10 UTC, apomalyn commented on lib/l10n/intl_en.arb
> +  "discovery_navbar_dashboard_page_details": "The Dashboard page groups together the most frequently consulted information, in the form of cards.\n\nIf you keep your finger on the card, you can move
```suggestion
  "discovery_navbar_dashboard_page_details": "The Dashboard page groups together the most frequently consulted information, in the form of cards.\n\nIf you keep your finger on the card, you can move it up and down to rearrange the cards.\n\nTo delete a card, swipe it to the left or right.",
```

2021-05-20 15:10 UTC, apomalyn commented on lib/l10n/intl_fr.arb
> +  "discovery_navbar_dashboard_page_details": "La page d'accueil regroupe les informations les plus fréquemment consultées, sous forme de cartes.\n\nEn gardant votre doigt sur la carte, vous pouvez le
```suggestion
  "discovery_navbar_dashboard_page_details": "La page d'accueil regroupe les informations les plus fréquemment consultées, sous forme de cartes.\n\nEn gardant votre doigt sur la carte, vous pouvez les déplacer vers le haut et vers le bas pour les réorganiser.\n\nPour supprimer une carte, simplement glisser la carte vers la gauche ou la droite.",
```

2021-05-22 14:23 UTC, AlexandreMarkus approved these changes

2021-05-22 15:03 UTC, apomalyn approved these changes
LGTM To me!!!! :smile: :1st_place_medal: :champagne:

2021-05-22 15:03 UTC, apomalyn approved these changes
LGTM To me!!!! :smile: :1st_place_medal: :champagne:

2021-05-22 17:19 UTC, merged