WIP: Change library to use flutter_customs_tabs
ApplETS/Notre-Dame pull request #374
Opened 2022-01-26 04:34 UTC by MysticFragilist

[flutter_customs_tabs](https://pub.dev/packages/flutter_custom_tabs) is much more maintained and seems more up to date than the package we were using before. I even put an animation on the page load with it 😄 

I can't really fully test the new package because of the bug right now. But as soon as I will be able to, I will drop some screenshot here :) At least for now, it doesn't crash on launch should be a good sign!

closes #304

2022-01-26 11:44 UTC, AlexandreMarkus requested changes

2022-01-29 20:54 UTC, MysticFragilist commented on lib/core/viewmodels/web_link_card_viewmodel.dart
> +          // ref. https://play.google.com/store/apps/details?id=org.mozilla.firefox
Yess good idea! I'll check that!

2022-01-29 20:55 UTC, MysticFragilist commented on lib/core/viewmodels/web_link_card_viewmodel.dart
> +            "WebLinkCardViewModel", "Error while launching url in tabs $error");
True true forgot about that one! 😅  I'll remove that then

2022-01-29 21:39 UTC, AlexandreMarkus approved these changes
LGTM!! Hopefully the browser will be more stable than before!

2022-01-29 23:29 UTC, MysticFragilist commented
> LGTM!! Hopefully the browser will be more stable than before!

I hope so too!

2022-01-30 18:55 UTC, eneiss approved these changes
LGTM 👌

2022-01-31 02:01 UTC, merged