Issues/357 Reload button in Dashboard page
ApplETS/Notre-Dame pull request #388
Opened 2022-02-07 06:55 UTC by Bretzoule

J'ai trouvé 2 façons de résoudre, mais celle ci reste la plus propre, on mettait déjà l'objet "courses" en mode "busy" mais jamais on allait vérifier que celui ci ne l'était plus pour mettre à jour la "card". J'ai donc rajouté une condition qui fait ça :brain:. 

L'autre solution c'était de checker si le cours était déjà dans la liste des cours actuel avant de l'afficher, mais cela pouvait casser l'organisation croissante des cours dans la card, donc bon...

Ça "fonctionne", c'est le principal I guess ?

Aussi, comme on en a parlé avec @MysticFragilist, concernant la liste des cours, des sessions, etc... le cache est sollicité à chaque fois, même si l'on a une connexion réseau. Cela n'a pas vraiment d'intêret car dans le cas ou on a internet on fini par faire la requête quand même. Il faudrait voir pour soit stocker une "version" avec une date de mise à jour et appeler l'API uniquement si notre version locale est oudated ou alors ignorer la lecture du cache dans le cas ou l'on a internet ! 

5h d'investigation pour... 17 caractères :sunglasses: . 

Closes #357

2022-02-07 14:58 UTC, eneiss submitted a review, later dismissed
Short and sweet 😄 LGTM!

2022-02-07 15:22 UTC, apomalyn requested changes
[Test test test...](https://media.giphy.com/media/gw3IWyGkC0rsazTi/giphy.gif) 😄

2022-03-27 17:41 UTC, MysticFragilist approved these changes
LGTM! :smile:

2022-03-27 19:11 UTC, eneiss approved these changes

2022-03-27 21:53 UTC, apomalyn approved these changes
LGTM!!

2022-03-27 22:06 UTC, merged