Fix infinite loading
ApplETS/Notre-Dame pull request #389
Opened 2022-02-08 03:45 UTC by MysticFragilist

Soooo I think I finally manage to find the bug that was making the cache throw an exception on launch (making the app unusable except if we cleared up the cache and storage of the app and starting over). :smile: @apomalyn look at [this thread](https://github.com/mogol/flutter_secure_storage/issues/43) in flutter_secure_storage repo! It's basically the same error that we have when an error occurs on startup. If this PR don't fix it, we will probably need to review the cache manager entirely. I have hopes tho!

### What this means
Right now, if a new version comes out and this bug happens on a device, the secure storage will be entirely wiped which means the user will have to login again.

However, it should prevent any new app download from having this issue from now on because of the change in the AndroidManifest.xml.

closes #387

2022-02-08 04:09 UTC, eneiss approved these changes
LGTM! Hope this will fix the issue 😊

2022-02-08 04:21 UTC, eneiss approved these changes
Looks even better to me 😆💯

2022-02-09 15:39 UTC, apomalyn requested changes
LGTM!! But... 
*put testing hat*
Could you modify the test already in place for the UserRepository so we could check the storage is correctly deleted when the exception is raised please 😄

2022-02-18 18:25 UTC, apomalyn commented
@MysticFragilist I just changed my phone and I'm hitting this issue, so when this will be available I could test it 😉

2022-02-18 18:32 UTC, MysticFragilist commented
> @MysticFragilist I just changed my phone and I'm hitting this issue, so when this will be available I could test it 😉 

Oh niiiice!

Je vais faire les tests en fin de semaine, ça devrait pas me prendre beaucoup de temps, je ferai une release tout de suite après :smile:

2022-02-20 01:21 UTC, AlexandreMarkus submitted a review, later dismissed

2022-02-21 00:44 UTC, AlexandreMarkus reviewed
I have a question, would it be possible, if the error occurs, to delete the secure storage but instead of asking the user to login again, try to login automatically since we already have the username and password in variables?

2022-02-21 00:44 UTC, AlexandreMarkus commented on lib/core/viewmodels/profile_viewmodel.dart
> +import 'package:notredame/locator.dart';
Good catch

2022-02-21 00:57 UTC, MysticFragilist commented
> I have a question, would it be possible, if the error occurs, to delete the secure storage but instead of asking the user to login again, try to login automatically since we already have the username and password in variables?

Yes it would be a great idea! I'll create the issue for this :) though I won't wait for this feature to be implemented as the bug is somewhat critical (some user can't even login and is probably the main cause for bad reviews right now 😅)

2022-02-21 03:26 UTC, AlexandreMarkus approved these changes

2022-02-21 15:41 UTC, apomalyn approved these changes
LGTM!!!

2022-02-21 17:07 UTC, merged