Fix the semester progression bar.
ApplETS/Notre-Dame pull request #447
Opened 2022-05-16 19:48 UTC by AntoineLemelin

Fix the issue #440 the progression now only accept value between 0 and daysInSessions.

Resolved #440

2022-05-17 18:59 UTC, MysticFragilist submitted a review, later dismissed
LGTM! Bonne idée pour le test aussi A1 😄 🚀

2022-05-19 23:01 UTC, MysticFragilist approved these changes

2022-05-19 23:08 UTC, MysticFragilist commented
tu peux rajouter "[CI UPDATE GOLDENS]" dans un message de commit pour que le CI regénére les goldens files. :smile:

2022-05-24 18:55 UTC, MysticFragilist requested changes

2022-05-24 18:55 UTC, MysticFragilist commented on pubspec.lock
> +    source: path
Même chose que dans l'autre PR ici! Essai de delete ton pubspec.lock et refait un flutter pub get ça devrait fix le prob 😄

2022-05-24 20:03 UTC, AntoineLemelin commented on pubspec.lock
> +    source: path
Je ne peux pas le delete (A cause des pod files de ios régénérer sur mac) j'oublie juste de ne pas le push...

2022-06-02 22:57 UTC, camillebrulotte approved these changes
LGTM :D

2022-07-07 23:09 UTC, MysticFragilist submitted a review, later dismissed

2022-07-07 23:12 UTC, camillebrulotte submitted a review, later dismissed
LGTM :D

2022-07-09 15:03 UTC, camillebrulotte approved these changes
lgtm

2022-07-09 15:03 UTC, MysticFragilist approved these changes

2022-07-09 15:35 UTC, merged