Fix the scaling of the webview for emergency
ApplETS/Notre-Dame pull request #448
Opened 2022-05-16 22:05 UTC by AntoineLemelin

I fix the html to scale the web view with the display size.

Resolved #417

2022-05-16 22:09 UTC, MysticFragilist commented
T'es en feu mec!! Hahaha good job 💯 je regarde tout ça dans pas long 😄

2022-05-17 00:28 UTC, eneiss submitted a review, later dismissed
LGTM 👌

2022-05-17 00:31 UTC, eneiss commented
@AntoineLemelin  Il faut juste que tu fix encore les erreurs de `flutter analyze` qui font fail les tests, mais à part ça tout a l'air top 💯

2022-05-17 00:45 UTC, AntoineLemelin commented
All is fix.

2022-05-17 19:06 UTC, MysticFragilist requested changes
Manque un petit merge de master dans toutes tes branches aussi mais sinon good job sur cette issue là 😄

2022-05-17 19:06 UTC, MysticFragilist commented on lib/core/viewmodels/emergency_viewmodel.dart
> +  }
il y aurait un test qu'on pourrait faire sur cette fonction je crois 😄 Aussi, si c'est pas tester ça serait peut-être pertinent d'ajouter aussi un test sur darkMode, t'en penses quoi?

2022-07-12 01:39 UTC, eneiss approved these changes

2022-07-13 16:08 UTC, eneiss approved these changes

2022-07-13 23:38 UTC, MysticFragilist approved these changes

2022-07-14 02:05 UTC, eneiss approved these changes

2022-07-14 04:21 UTC, eneiss approved these changes

2022-07-14 12:29 UTC, MysticFragilist approved these changes
LGTM!

2022-07-14 13:41 UTC, merged