Fix the "Rate us" button not doing anything
ApplETS/Notre-Dame pull request #470
Opened 2022-06-04 16:14 UTC by HugoMigner

Potential solution for #469 

Instead of opening the in-app dialog for reviews, it redirects to the phone's app store.

This is due to an issue with the "in_app_review" flutter package where you can't show the in-app dialog too often, see [here](https://pub.dev/packages/in_app_review#requestreview)

2022-06-05 13:23 UTC, camillebrulotte approved these changes
LGTM :D

2022-06-05 13:27 UTC, camillebrulotte requested changes
OOps j'avais pas vue que les tests passaient plus hahaha

2022-06-08 22:41 UTC, MysticFragilist requested changes
Micro changement mais sinon goooood job!!! 😄

2022-06-08 22:41 UTC, MysticFragilist commented on lib/core/constants/more_ids.dart
> +class MoreIds {
T'en penses quoi qu'on call ce fichier d'une autre manière, peut-être app_info.dart serait bien (on pourrait ultimement rajouter android id si jamais on en a besoin)?

2022-06-08 23:22 UTC, HugoMigner commented on lib/core/constants/more_ids.dart
> +class MoreIds {
Oui bonne idée!

2022-06-08 23:29 UTC, MysticFragilist approved these changes
LGTM! 🚀 😄

2022-06-08 23:37 UTC, camillebrulotte approved these changes
LGTM 😊

2022-06-08 23:43 UTC, merged