Feature/need help button login page
ApplETS/Notre-Dame pull request #477
Opened 2022-06-10 00:41 UTC by camillebrulotte

<img src="https://user-images.githubusercontent.com/37625944/172967525-b4a24108-a0cb-47c7-b99c-aa67d2a3169e.png"  width="300"/>

<img src="https://user-images.githubusercontent.com/37625944/172967547-d198a703-ab33-4524-aa39-ea3c3a2f63a4.png"  width="300"/>

<img src="https://user-images.githubusercontent.com/37625944/172967751-f8b88fb9-3b9f-4c0d-8607-24ab03061501.png"  width="300"/>

2022-06-10 15:31 UTC, HugoMigner requested changes

2022-06-10 15:31 UTC, HugoMigner commented on lib/ui/views/login_view.dart
> +      "mailto:applets@etsmtl.net?subject=Problème ÉTS Mobile";
On pourrait peut-être sortir cette string et la mettre dans un fichier constante 😮. J'en ai créé un dans ma dernière PR: 

`lib\core\constants\app_info.dart`

Ça permettrait peut-être aussi de changer le `?subject=Problème ÉTS Mobile` pour une string traduite FR/EN aussi!

2022-06-10 15:39 UTC, MysticFragilist commented on lib/ui/views/login_view.dart
> +      "mailto:applets@etsmtl.net?subject=Problème ÉTS Mobile";
même en rajoutant à ça:

on pourrait passer en paramètre le email et le subject avec une string du genre:
```dart
public mailtoStr(String email, String subject) {
  return 'mailto:{email}?subject={subject}';
}
``` 

dans le viewmodel et depuis le login_view on l'utilise comme ça:
```dart
model.mailtoStr(AppInfo.email, AppIntl.of(context).email_subject);
```

Et ça serait facilement testable! 😄

2022-07-14 02:39 UTC, Udito3 approved these changes
LGTM 😁👌

2022-07-14 02:51 UTC, MysticFragilist requested changes
Un petit comment mais sinon good job! LGTM quand fix :)

2022-07-14 02:51 UTC, MysticFragilist commented on lib/ui/views/login_view.dart
> +    final urllaunchable = await _launchUrlService.canLaunchUrl(clubEmail);
```suggestion
    final urlLaunchable = await _launchUrlService.canLaunchUrl(clubEmail);
```

2022-07-14 03:07 UTC, MysticFragilist approved these changes
LGTM ! 🚀

2022-07-14 03:08 UTC, Udito3 approved these changes

2022-07-14 03:17 UTC, merged