Add scrolling title when opening evaluation
ApplETS/Notre-Dame pull request #479
Opened 2022-06-13 23:37 UTC by HugoMigner

Closes #471 

This PR adds scrolling titles to individual evaluations in the Student section of the app.

When an evaluation had a long title, it was impossible to see it in its entirety. Now, when the evaluation sub-menu is opened, the title will scroll, allowing the user to read it.

![Marquee](https://user-images.githubusercontent.com/48542098/173464434-7f75c937-27ed-443d-a52b-e99ed127da4f.gif)

2022-06-14 02:28 UTC, MysticFragilist requested changes

2022-06-14 02:28 UTC, MysticFragilist commented on lib/ui/widgets/grade_evaluation_tile.dart
> +                  if (!showEvaluationDetails)
Je sais pas si c'est possible, mais il faudrait s'assurer de montrer le marquee uniquement quand le texte est trop long pour être lu. Je sais pas si il y aurait une manière de savoir si le texte overflow avec les '...' pour démarrer le marquee dessus. 😄 T'en penses quoi?

2022-06-14 14:09 UTC, HugoMigner commented on lib/ui/widgets/grade_evaluation_tile.dart
> +                  if (!showEvaluationDetails)
J'y avais pensé aussi! Mais je pense que le overflow embarque tout seul quand le texte est trop long, y'a comme pas de façon de le contrôler je pense... Je pourrais faire en sorte que ça scroll si le titre a un certain nombre de caractères, mais c'est plus rough au dirait 😅

2022-06-18 00:44 UTC, MysticFragilist commented on lib/ui/widgets/grade_evaluation_tile.dart
> +                  if (!showEvaluationDetails)
J'sais pas si ça peut aider, mais j'ai trouver ça: 
![image](https://user-images.githubusercontent.com/25663435/174415596-cc5dc706-5f52-4818-b0b1-1295a4351bce.png)

2022-07-08 01:15 UTC, HugoMigner commented
J'ai trouvé ça ici pour handle les overflow !

https://pub.dev/packages/auto_size_text#overflowreplacement

Dit moi ce que t'en penses @MysticFragilist !

2022-07-17 00:35 UTC, AntoineLemelin approved these changes
LGTM!

2022-07-19 19:17 UTC, MysticFragilist requested changes

2022-07-19 19:17 UTC, MysticFragilist commented on lib/ui/widgets/grade_evaluation_tile.dart
> +                            blankSpace: 200,
Est-ce que le blank space avait été changé finalement? si non on pourrait essayer 100 ou 150 :)

2022-07-23 14:42 UTC, HugoMigner commented
Vidéo!

https://user-images.githubusercontent.com/48542098/180609902-032136b0-d53a-4056-b852-4370e1abdd93.mp4

2022-07-23 14:45 UTC, HugoMigner commented on lib/ui/widgets/grade_evaluation_tile.dart
> +                            blankSpace: 200,
C'est fait! J'ai changé ça a 50!

2022-08-07 01:32 UTC, apomalyn commented
@HugoMigner quick question, the animation start only if the title is cut?

2022-08-07 01:56 UTC, HugoMigner commented
> 

Yes! The prop `overflowReplacement` will only render if the original text overflows!

2022-09-10 14:42 UTC, camillebrulotte approved these changes
Trop fort

2022-09-10 14:42 UTC, AntoineLemelin approved these changes
LGTM !

2022-09-10 14:42 UTC, MysticFragilist approved these changes
LGTM!

2022-09-10 14:42 UTC, merged