Feature/outage page
ApplETS/Notre-Dame pull request #492
Opened 2022-07-07 16:48 UTC by AntoineLemelin

2022-07-08 04:38 UTC, apomalyn commented
@AntoineLemelin est-ce que tu pourrais ajouter une description avec screenshot/gif STP 😄

2022-07-11 03:36 UTC, eneiss requested changes

2022-07-11 03:36 UTC, eneiss commented on l10n/intl_fr.arb
> +  "service_outage_contact": "Si le problème persiste vous pouvez nous contacter: ",
Il y a une petite faute ici, c'est "Désolé" (ou peut-être "Désolés" ?) au lieu de "Désoler" 😅 
Et j'aurais mis une virgule juste après "Désolé(s?)", puis peut-être entre "Si le problème persiste" et "vous pouvez nous contacter" (mais là c'est vraiment picky et pas forcément nécessaire 😂 )

Good job en tout cas ! J'ai pas fini de review (😴) mais ça a l'air good 👌

2022-07-13 14:11 UTC, eneiss submitted a review, later dismissed
LGTM ! 💯 
Vraiment good job, ça va être bien pratique tout ça 😁 
Ça serait peut-être juste bien de tester `RemoteConfigService` et `OutageViewModel`, tu penses que tu peux le faire ?

2022-07-14 03:20 UTC, eneiss approved these changes

2022-07-27 16:53 UTC, MysticFragilist requested changes
good job! petits comments apres discussion! 😄

2022-07-27 16:53 UTC, MysticFragilist commented on lib/core/services/remote_config_service.dart
> +    await _remoteConfig.fetchAndActivate();
caller 'fetch()'

2022-07-27 16:53 UTC, MysticFragilist commented on lib/core/services/remote_config_service.dart
> +    await _remoteConfig.fetchAndActivate();
try catch et logger avec analytics

2022-08-07 00:29 UTC, eneiss commented on lib/core/services/remote_config_service.dart
> +import 'package:flutter/foundation.dart';
Il faut que tu fix ton `flutter analyze`, cet import est pas utilisé apparemment

2022-08-09 02:46 UTC, eneiss requested changes
Deux trois petits trucs qui pourraient être améliorés mais c'est vraiment nice sinon ! Good job 💯 
Hâte de voir ça dans l'app (mais pas trop non plus, c'est mieux quand les services sont up haha 😆 )

2022-08-09 02:46 UTC, eneiss commented on lib/core/services/navigation_service.dart
> +import 'package:notredame/locator.dart';
Ca serait nice de trier les imports comme tu l'as fait dans le fichier `outage_view.dart` (ceci dit ligne 3 c'est pas ta faute on dirait 😅 )

2022-08-09 02:46 UTC, eneiss commented on lib/core/services/remote_config_service.dart
> +import 'package:notredame/locator.dart';
Pareil ici

2022-08-09 02:46 UTC, eneiss commented on lib/core/viewmodels/outage_viewmodel.dart
> +import 'package:stacked/stacked.dart';
Pareil ici

2022-08-09 02:46 UTC, eneiss commented on lib/ui/views/outage_view.dart
> +import 'package:notredame/core/constants/urls.dart';
Ici tu peux mettre app_theme dans `// UTILS` et constants dans `// CONSTANTS`

2022-08-09 02:46 UTC, eneiss commented on lib/core/services/remote_config_service.dart
> +  static const String tag = "RmoteConfigService";
Je sais pas si la typo dans le tag se fix bien ou si c'est déjà comme ça dans Firebase, mais si c'est facile à fix ça peut être nice 🙂

2022-08-12 22:09 UTC, eneiss approved these changes
C'est parfait, good job 🚀 
Et désolée d'avoir trouvé les problèmes d'import un peu tard 😅

2022-08-23 17:40 UTC, camillebrulotte approved these changes
LGTM :D

2022-08-24 15:44 UTC, MysticFragilist submitted a review, later dismissed
LGTM!

2022-08-28 14:22 UTC, eneiss approved these changes
LGTM 🔥

2022-09-06 02:51 UTC, MysticFragilist approved these changes
LGTM!

2022-09-06 02:51 UTC, merged