fix #500 - change portail URL to bypass MFA warning page
ApplETS/Notre-Dame pull request #501
Opened 2022-07-25 15:48 UTC by jfl3x

2022-07-25 16:29 UTC, AlexandreMarkus submitted a review, later dismissed
Lgtm!!

2022-07-26 19:51 UTC, MysticFragilist requested changes
Discuter avec @jfl3x, mais il y a la version dans le `pubspec.yaml` qu'il faut bumper 😄 comme c'est un bug fix, je conseillerais que ce soit la patch qui soit updaté (4.12.5)! LMK si ya autre chose sinon c'est LGTM! 👍

2022-07-26 20:32 UTC, MysticFragilist commented
Aussi je te l'avais pas dit @jfl3x, mais en gros quand ta PR est approuvé par 2 personnes et que les checks du CI passe, tu peux la merger! On laisse la responsabilité (et l'honneur 😉) de merger son fix :)

Ahh ouii et last one hahaha (sorry j'ai pas mal oublié de te dire de trucs pour la PR 😅) Comme on travaille en mode open source, on essaye du mieux qu'on peut de rajouter une petite description dans nos PR pour que quelqu'un qui est pas dans le club soit capable de retracer notre avancement. Pour celle-ci c'est pas trop grave vu que ce n'est pas un gros fix la description est dans le titre, mais pour next time :)

2022-09-10 17:53 UTC, MysticFragilist approved these changes
LGTM! :rocket:

2022-09-10 17:58 UTC, Udito3 approved these changes
LGTM too 😄

2022-09-10 21:59 UTC, eneiss approved these changes
LGTM 💯

2022-09-19 18:07 UTC, merged

2022-09-26 20:31 UTC, SimonR99 commented
Good job jf !