Feature/splash screen
ApplETS/Notre-Dame pull request #58
Opened 2021-03-08 17:11 UTC by camillebrulotte

Sur IOS : 
https://user-images.githubusercontent.com/37625944/110355201-f72cce80-8006-11eb-8351-877d033cfb4e.mp4

Sur Android : 
https://user-images.githubusercontent.com/37625944/110355205-f8f69200-8006-11eb-9e28-86d5f1e44511.mp4

2021-03-08 18:33 UTC, apomalyn commented
Will close #54

2021-03-08 20:33 UTC, AlexandreMarkus reviewed
nice improvement!

2021-03-08 20:33 UTC, AlexandreMarkus commented on ios/Flutter/.last_build_id
> +cdfadc782a1cf1a6b0f70bd8b6b32e50
is this file needed?

2021-03-08 20:46 UTC, camillebrulotte commented on ios/Flutter/.last_build_id
> +cdfadc782a1cf1a6b0f70bd8b6b32e50
Effectivement nop, merci!

2021-03-08 20:53 UTC, apomalyn commented
It's a nice implementation 🥇 
LGTM to me! 🎉 

And congrats on your first contribution!!!

2021-03-08 20:57 UTC, apomalyn reviewed
LGTM but I have one little request :D that will give you some code to write :D 

Could you test if a dark version of the splash screen (and also startup_view) could be implemented? ^^

2021-03-09 14:39 UTC, AlexandreMarkus commented
> LGTM but I have one little request  that will give you some code to write 
> 
> Could you test if a dark version of the splash screen (and also startup_view) could be implemented?

What color do you mean? I think the red color matches light and dark themes pretty well ? ;)

2021-03-09 19:04 UTC, apomalyn commented
> > LGTM but I have one little request  that will give you some code to write
> > Could you test if a dark version of the splash screen (and also startup_view) could be implemented?
> 
> What color do you mean? I think the red color matches light and dark themes pretty well ? ;)

It's working yes, if you check the beta version there splash screen is black and not red. I think it's very pleasant especially when you are in a dark room (aka your bed at 3 a.m. :sweat_smile:). But if everyone is ok with the red version, I'm good with it :smiley:

2021-03-09 19:53 UTC, AlexandreMarkus commented
> > > LGTM but I have one little request  that will give you some code to write
> > > Could you test if a dark version of the splash screen (and also startup_view) could be implemented?
> > 
> > 
> > What color do you mean? I think the red color matches light and dark themes pretty well ? ;)
> 
> It's working yes, if you check the beta version there splash screen is black and not red. I think it's very pleasant especially when you are in a dark room (aka your bed at 3 a.m. ). But if everyone is ok with the red version, I'm good with it

True, in that case, I would go with your idea of adding a dark theme

2021-03-09 20:01 UTC, camillebrulotte commented
> > > > LGTM but I have one little request  that will give you some code to write
> > > > Could you test if a dark version of the splash screen (and also startup_view) could be implemented?
> > > 
> > > 
> > > What color do you mean? I think the red color matches light and dark themes pretty well ? ;)
> > 
> > 
> > It's working yes, if you check the beta version there splash screen is black and not red. I think it's very pleasant especially when you are in a dark room (aka your bed at 3 a.m. ). But if everyone is ok with the red version, I'm good with it
> 
> True, in that case, I would go with your idea of adding a dark theme

Yes ! En ce moment la couleur prise en Dark Theme est le gris/noir. 
(Pour l'instant il affiche les deux thèmes (en rouge et en noir). Donc, il me reste à fix qu'il n'en affiche qu'un). 

Est-ce que pour le dark theme ça vous va le background en noir avec le logo rouge ? Ou je laissais le logo blanc ? 

https://user-images.githubusercontent.com/37625944/110529799-accf4e80-80e7-11eb-931a-20d4e3bbac30.mov

2021-03-10 21:37 UTC, camillebrulotte commented
@AlexandreMarkus  @apomalyn 

Présentement, le dark/light theme du splash screen se fait switch en fonction du theme dans les configs du téléphone. 

J'ai pas encore réussie à le faire sur Android mais sur ios, tout ce fait dans les configs dans xCode. Pour permettre que le thème chance en fonction de ce qui est sélectionner dans les "settings" de l'application, il faudrait écrire du code en swift et ça prendrait beaucoup de temps selon moi pour ce que ça apporte. 

Est-ce que je le laisse comme ça ou c'est mieux de juste complètement enlever le dark theme du splash screen ? 

Si c'est correcte que ce soit basé sur le theme du téléphone et non celle de l'app, pour que ça fit bien, le startupview fonctionnerait de la même manière que le splash screen.

2021-03-10 22:26 UTC, apomalyn commented
> @AlexandreMarkus @apomalyn
> 
> Présentement, le dark/light theme du splash screen se fait switch en fonction du theme dans les configs du téléphone.
> 
> J'ai pas encore réussie à le faire sur Android mais sur ios, tout ce fait dans les configs dans xCode. Pour permettre que le thème chance en fonction de ce qui est sélectionner dans les "settings" de l'application, il faudrait écrire du code en swift et ça prendrait beaucoup de temps selon moi pour ce que ça apporte.
> 
> Est-ce que je le laisse comme ça ou c'est mieux de juste complètement enlever le dark theme du splash screen ?
> 
> Si c'est correcte que ce soit basé sur le theme du téléphone et non celle de l'app, pour que ça fit bien, le startupview fonctionnerait de la même manière que le splash screen.

Pour le splash screen light/dark sur Android, tu peux check cet [article](https://medium.com/flutter-community/splash-screens-for-dark-and-light-mode-in-flutter-eb85f1aa025).

Il est très probable que l'utilisateur qui a son système en dark mode utilise l'application également en dark mode, donc je serait plutôt pour le fait de garder un dark/light mode sur le splash screen et sur la startup_view (et donc cette dernière suivrait le thème set dans l'application). Le splash screen disparait en fondu donc le switch de light <-> dark est plutôt seamless. 

En bref: je suis d'avis d'avoir un splash screen light et dark 😄  est-ce que ça fait du sens?

2021-03-10 22:58 UTC, camillebrulotte commented
> > @AlexandreMarkus @apomalyn
> > Présentement, le dark/light theme du splash screen se fait switch en fonction du theme dans les configs du téléphone.
> > J'ai pas encore réussie à le faire sur Android mais sur ios, tout ce fait dans les configs dans xCode. Pour permettre que le thème chance en fonction de ce qui est sélectionner dans les "settings" de l'application, il faudrait écrire du code en swift et ça prendrait beaucoup de temps selon moi pour ce que ça apporte.
> > Est-ce que je le laisse comme ça ou c'est mieux de juste complètement enlever le dark theme du splash screen ?
> > Si c'est correcte que ce soit basé sur le theme du téléphone et non celle de l'app, pour que ça fit bien, le startupview fonctionnerait de la même manière que le splash screen.
> 
> Pour le splash screen light/dark sur Android, tu peux check cet [article](https://medium.com/flutter-community/splash-screens-for-dark-and-light-mode-in-flutter-eb85f1aa025).
> 
> Il est très probable que l'utilisateur qui a son système en dark mode utilise l'application également en dark mode, donc je serait plutôt pour le fait de garder un dark/light mode sur le splash screen et sur la startup_view (et donc cette dernière suivrait le thème set dans l'application). Le splash screen disparait en fondu donc le switch de light <-> dark est plutôt seamless.
> 
> En bref: je suis d'avis d'avoir un splash screen light et dark 😄 est-ce que ça fait du sens?

Je crois que oui, je vais essayer ça merci ! 
Si j'ai bien comprise, je rajoute un fondu avant que la startup_view apparaît étant donné que lui va changer de thème en fonction du thème sélectionner dans les settings de l'app et non en fonction du thème du téléphone ?

2021-03-10 23:06 UTC, apomalyn commented
> > > @AlexandreMarkus @apomalyn
> > > Présentement, le dark/light theme du splash screen se fait switch en fonction du theme dans les configs du téléphone.
> > > J'ai pas encore réussie à le faire sur Android mais sur ios, tout ce fait dans les configs dans xCode. Pour permettre que le thème chance en fonction de ce qui est sélectionner dans les "settings" de l'application, il faudrait écrire du code en swift et ça prendrait beaucoup de temps selon moi pour ce que ça apporte.
> > > Est-ce que je le laisse comme ça ou c'est mieux de juste complètement enlever le dark theme du splash screen ?
> > > Si c'est correcte que ce soit basé sur le theme du téléphone et non celle de l'app, pour que ça fit bien, le startupview fonctionnerait de la même manière que le splash screen.
> > 
> > 
> > Pour le splash screen light/dark sur Android, tu peux check cet [article](https://medium.com/flutter-community/splash-screens-for-dark-and-light-mode-in-flutter-eb85f1aa025).
> > Il est très probable que l'utilisateur qui a son système en dark mode utilise l'application également en dark mode, donc je serait plutôt pour le fait de garder un dark/light mode sur le splash screen et sur la startup_view (et donc cette dernière suivrait le thème set dans l'application). Le splash screen disparait en fondu donc le switch de light <-> dark est plutôt seamless.
> > En bref: je suis d'avis d'avoir un splash screen light et dark smile est-ce que ça fait du sens?
> 
> Je crois que oui, je vais essayer ça merci !
> Si j'ai bien comprise, je rajoute un fondu avant que la startup_view apparaît étant donné que lui va changer de thème en fonction du thème sélectionner dans les settings de l'app et non en fonction du thème du téléphone ?

Tu n'as pas a faire de fondu, Flutter le gère tout seul (du moins pour Android, iOS j'ai pas vérifié) :smile: Tant que ton splash screen possède les bonnes meta-data le fondu devrait se faire automatiquement, check [ici](https://flutter.dev/docs/development/ui/advanced/splash-screen#android-launch-screen) au besoin :smile: au pire c'est pas grave si il y a pas de fondu

2021-03-11 00:07 UTC, camillebrulotte commented
> > > > @AlexandreMarkus @apomalyn
> > > > Présentement, le dark/light theme du splash screen se fait switch en fonction du theme dans les configs du téléphone.
> > > > J'ai pas encore réussie à le faire sur Android mais sur ios, tout ce fait dans les configs dans xCode. Pour permettre que le thème chance en fonction de ce qui est sélectionner dans les "settings" de l'application, il faudrait écrire du code en swift et ça prendrait beaucoup de temps selon moi pour ce que ça apporte.
> > > > Est-ce que je le laisse comme ça ou c'est mieux de juste complètement enlever le dark theme du splash screen ?
> > > > Si c'est correcte que ce soit basé sur le theme du téléphone et non celle de l'app, pour que ça fit bien, le startupview fonctionnerait de la même manière que le splash screen.
> > > 
> > > 
> > > Pour le splash screen light/dark sur Android, tu peux check cet [article](https://medium.com/flutter-community/splash-screens-for-dark-and-light-mode-in-flutter-eb85f1aa025).
> > > Il est très probable que l'utilisateur qui a son système en dark mode utilise l'application également en dark mode, donc je serait plutôt pour le fait de garder un dark/light mode sur le splash screen et sur la startup_view (et donc cette dernière suivrait le thème set dans l'application). Le splash screen disparait en fondu donc le switch de light <-> dark est plutôt seamless.
> > > En bref: je suis d'avis d'avoir un splash screen light et dark smile est-ce que ça fait du sens?
> > 
> > 
> > Je crois que oui, je vais essayer ça merci !
> > Si j'ai bien comprise, je rajoute un fondu avant que la startup_view apparaît étant donné que lui va changer de thème en fonction du thème sélectionner dans les settings de l'app et non en fonction du thème du téléphone ?
> 
> Tu n'as pas a faire de fondu, Flutter le gère tout seul (du moins pour Android, iOS j'ai pas vérifié) 😄 Tant que ton splash screen possède les bonnes meta-data le fondu devrait se faire automatiquement, check [ici](https://flutter.dev/docs/development/ui/advanced/splash-screen#android-launch-screen) au besoin 😄 au pire c'est pas grave si il y a pas de fondu

Est-ce qu'on avait le logo en rouge ? Pour l'instant j'ai changé la couleur blanc pour en rouge avec Krita mais j'ai l'impression que le logo a l'air flou comparé au blanc

![image](https://user-images.githubusercontent.com/37625944/110715628-9f8f8e00-81d3-11eb-865d-4c41fd36071a.png)

2021-03-11 15:16 UTC, AlexandreMarkus commented
> @AlexandreMarkus @apomalyn
> 
> Présentement, le dark/light theme du splash screen se fait switch en fonction du theme dans les configs du téléphone.
> 
> J'ai pas encore réussie à le faire sur Android mais sur ios, tout ce fait dans les configs dans xCode. Pour permettre que le thème chance en fonction de ce qui est sélectionner dans les "settings" de l'application, il faudrait écrire du code en swift et ça prendrait beaucoup de temps selon moi pour ce que ça apporte.
> 
> Est-ce que je le laisse comme ça ou c'est mieux de juste complètement enlever le dark theme du splash screen ?
> 
> Si c'est correcte que ce soit basé sur le theme du téléphone et non celle de l'app, pour que ça fit bien, le startupview fonctionnerait de la même manière que le splash screen.

For your info, this is the current behaviour of Notre-Dame 3.0, so I think this is great :smiley:

2021-03-11 21:47 UTC, apomalyn commented
@camillebrulotte very good job! There is just a little comment \**put on my accessibility hat*\* the button 'se connecter' should be grey only when 'not clickable'.
<img width="378" alt="Screen Shot 2021-03-11 at 4 25 07 PM" src="https://user-images.githubusercontent.com/22211097/110857079-649a6280-8286-11eb-88bf-cab17d296c1e.png">
<img width="378" alt="Screen Shot 2021-03-11 at 4 25 22 PM" src="https://user-images.githubusercontent.com/22211097/110857082-67955300-8286-11eb-9720-607248709f78.png">

But as you can see, the active state of the button is a lighter grey than when non-active. This is not a really great user experience. After some tests, I propose this:

https://user-images.githubusercontent.com/22211097/110859377-53068a00-8289-11eb-8e3f-ec410a947e10.mov

What do you think about this?

2021-03-11 21:48 UTC, camillebrulotte commented
> @camillebrulotte very good job! There is just a little comment \**put on my accessibility hat*\* the button 'se connecter' should be grey only when 'not clickable'.
> 
> <img width="378" alt="Screen Shot 2021-03-11 at 4 25 07 PM" src="https://user-images.githubusercontent.com/22211097/110857079-649a6280-8286-11eb-88bf-cab17d296c1e.png">
> 
> <img width="378" alt="Screen Shot 2021-03-11 at 4 25 22 PM" src="https://user-images.githubusercontent.com/22211097/110857082-67955300-8286-11eb-9720-607248709f78.png">
> 
> 
> 
> But as you can see, the active state of the button is a lighter grey than when non-active. This is not a really great user experience. After some tests, I propose this:
> 
> 
> 
> https://user-images.githubusercontent.com/22211097/110859377-53068a00-8289-11eb-8e3f-ec410a947e10.mov
> 
> 
> 
> What do you think about this?

Yes j'suis d'accord :D

2021-03-11 22:23 UTC, apomalyn commented
Do you want me to push the changes or you do it? 😄

2021-03-11 23:31 UTC, camillebrulotte commented
> Do you want me to push the changes or you do it? 😄

Yes si ça ne te dérange pas ! Merci :)

2021-03-12 00:48 UTC, AlexandreMarkus approved these changes
I approve! Good job!
@apomalyn Is it good for you too?

2021-03-12 00:57 UTC, apomalyn requested changes
Ok, I have a question, that change some part of your code. 😅  Except for these changes (these are all the same by the way), it will be good 😄

2021-03-12 00:57 UTC, apomalyn commented on lib/ui/views/login_view.dart
> +                        : AppTheme.primaryDark,
What? XD
```
if appSetting.theme is light:
    etsLightRed
else:
    if appSetting.theme is dark:
        primaryDark
    else:
        if theme.brightness is light:
            etsLightRed
        else:
            primaryDark
```

It's a bit overkill no? XD `Theme.of(context).brightness` is always representing the actual theme of the application

```suggestion
            backgroundColor: Theme.of(context).brightness == Brightness.light
                        ? AppTheme.etsLightRed
                        : AppTheme.primaryDark,
```

This should be enough I think 😄

2021-03-12 00:57 UTC, apomalyn commented on lib/ui/views/login_view.dart
> +                                              : "assets/images/ets_red_logo.png",
Same here. Did you found a case where this is needed? 🤔 
```suggestion
                                  Theme.of(context).brightness ==
                                                  Brightness.light
                                              ? "assets/images/ets_white_logo.png"
                                              : "assets/images/ets_red_logo.png",
```

2021-03-12 00:57 UTC, apomalyn commented on lib/ui/views/login_view.dart
> +  }
```suggestion
  Color get errorTextColor => Theme.of(context).brightness == Brightness.light
                ? Colors.amberAccent
                : Colors.redAccent;
  }
```

Could be a getter 😄

2021-03-12 00:57 UTC, apomalyn commented on lib/ui/views/login_view.dart
> +                                              model.getAppTheme()),
```suggestion
                                          color: errorTextColor,
```

If you apply the change below 👇

2021-03-12 00:57 UTC, apomalyn commented on lib/ui/views/login_view.dart
> +                                              model.getAppTheme()),
```suggestion
                                          color: errorTextColor,
```

If you apply the change below 👇  (again)

2021-03-12 00:57 UTC, apomalyn commented on lib/ui/views/login_view.dart
> +                                          model.getAppTheme())),
```suggestion
                                      color: errorTextColor,
```

If you apply the change below 👇  (again x2)

2021-03-12 00:57 UTC, apomalyn commented on lib/ui/views/login_view.dart
> +                                              Colors.grey[800]);
With the example, I showed you this section should be revert as:
```suggestion
                                          return Colors.white38;
```

2021-03-12 00:57 UTC, apomalyn commented on lib/ui/views/login_view.dart
> +  }
```suggestion
  Color get buttonColor => Theme.of(context).brightness == Brightness.light
                ? Colors.white
                : AppTheme.etsLightRed;
```

Same thing of getErrorTextColor 😄

2021-03-12 00:57 UTC, apomalyn commented on lib/ui/views/login_view.dart
> +                                            Colors.grey[900]);
```suggestion
                                        return buttonColor;
```

If you apply the fixes below 👇  😄

2021-03-12 00:57 UTC, apomalyn commented on lib/ui/views/startup_view.dart
> +                                : AppTheme.primaryDark,
```suggestion
                    Theme.of(context).brightness == Brightness.light
                                ? AppTheme.etsLightRed
                                : AppTheme.primaryDark,
```

2021-03-12 00:57 UTC, apomalyn commented on lib/ui/views/startup_view.dart
> +                                        : "assets/images/ets_red_logo.png",
```suggestion
                            Theme.of(context).brightness ==
                                            Brightness.light
                                        ? "assets/images/ets_white_logo.png"
                                        : "assets/images/ets_red_logo.png",
```

2021-03-12 00:57 UTC, apomalyn commented on lib/ui/widgets/password_text_field.dart
> +  }
```suggestion

  Color get errorTextColor => Theme.of(context).brightness == Brightness.light
                ? Colors.amberAccent
                : Colors.redAccent;
```

Same as login_view.dart

2021-03-12 00:57 UTC, apomalyn commented on lib/ui/widgets/password_text_field.dart
> +                    color: getErrorTextColor(), width: borderRadiusOnFocus)),
```suggestion
                    color: errorTextColor, width: borderRadiusOnFocus)),
```

If you apply the change below 👇

2021-03-12 00:57 UTC, apomalyn commented on lib/ui/widgets/password_text_field.dart
> +                    color: getErrorTextColor(), width: borderRadiusOnFocus)),
```suggestion
                    color: errorTextColor, width: borderRadiusOnFocus)),
```

If you apply the change below 👇

2021-03-12 00:57 UTC, apomalyn commented on lib/ui/widgets/password_text_field.dart
> +            errorStyle: TextStyle(color: getErrorTextColor()),
```suggestion
            errorStyle: TextStyle(color: errorTextColor),
```

If you apply the change below 👇

2021-03-12 00:57 UTC, apomalyn commented on lib/ui/widgets/password_text_field.dart
> +  final String appTheme;
No need for that because you have access to context

2021-03-12 01:00 UTC, apomalyn commented
> > Do you want me to push the changes or you do it? 😄
> 
> Yes si ça ne te dérange pas ! Merci :)

I was reviewing the PR sorry XD I will push it right away

2021-03-12 02:44 UTC, apomalyn approved these changes
I applied all the changes we discussed. LGTM !! 🎉 🍾  

I suggest @camillebrulotte to validate I didn't forget anything and after that you can merge your PR (and delete the branch)😄

2021-03-12 20:55 UTC, merged