Feature/quicklink rubiks
ApplETS/Notre-Dame pull request #59
Opened 2021-03-08 17:31 UTC by JonathanDuvalV

Je n'étais pas certains pour l'icon, j'ai choisi celui la
![image](https://user-images.githubusercontent.com/45638733/110357930-d1ed8f80-8009-11eb-9d4a-b1eaeda7a6b3.png)

2021-03-08 17:34 UTC, camillebrulotte commented on lib/l10n/intl_fr.arb
> +  "ets_schedule_generator": "Rubiks",
Leur site ne semble pas avoir de "s" dans leur nom. Faurais peut-être l'enlever ? 

http://rubik.clubnaova.ca/

2021-03-08 18:49 UTC, apomalyn commented
On hold until #57 is merged

2021-03-08 20:40 UTC, AlexandreMarkus commented on lib/l10n/intl_en.arb
> +  "ets_schedule_generator": "Rubiks",
```suggestion
  "ets_schedule_generator": "Rubik",
```

2021-03-08 20:40 UTC, AlexandreMarkus commented on lib/l10n/intl_fr.arb
> +  "ets_schedule_generator": "Rubiks",
```suggestion
  "ets_schedule_generator": "Rubik",
```

2021-03-08 20:42 UTC, apomalyn commented
> DO NOT MERGE!
> On hold until #57 is merged, I will review it later today or tomorrow 😄

#57 is merged! Will merge this PR when approved.

2021-03-09 19:12 UTC, apomalyn requested changes
Please pull master into your branch :smiley: otherwise I don't have anything to add :+1:

2021-03-12 01:42 UTC, JonathanDuvalV commented
> Please pull master into your branch 😃 otherwise I don't have anything to add 👍

Sorry about that 😅. I was busy in the last few days. Merged master into the branch and fixed to use correct title for the rubik link.

2021-03-12 01:42 UTC, JonathanDuvalV commented
Also it looks like Prettier changed the formating on the quicklinks file. Sorry about that

2021-03-12 15:42 UTC, apomalyn approved these changes
LGTM! 🍾 🎉

2021-03-12 18:58 UTC, merged