Feature/discovery/choose language modal
ApplETS/Notre-Dame pull request #67
Opened 2021-03-14 21:10 UTC by camillebrulotte

**#66 is merged in this branch. #66 needs to be merged before.** 
The base branch use is the main_discovery to not show all the duplicate changes. 
But, this branch will ultimately be merged in master.

In the video, after selecting the language, the app is navigating to the schedule page. Normally, it will show the dashboard page.

https://user-images.githubusercontent.com/37625944/111083708-31a1da00-84e5-11eb-9263-1ddd18b43bdc.mp4

![image](https://user-images.githubusercontent.com/37625944/111083867-fc49bc00-84e5-11eb-9863-88031a2de5af.png)

2021-03-15 17:10 UTC, MysticFragilist requested changes

2021-03-15 17:10 UTC, MysticFragilist commented on test/ui/views/choose_language_view_test.dart
> +    tearDown(() {});
I'm not sure, but I think in the tearDown, you need to call `unregister<OneOfTheServiceYouUsed>();` for each service you have setup (I found an example [here](https://github.com/ApplETS/Notre-Dame/blob/master/test/ui/views/login_view_test.dart))

2021-03-22 02:39 UTC, apomalyn requested changes
Because this would probably be the first screen you see after your first login I think a popup isn't the best way to present this information. 

What do you think about a screen instead of a modal? After this screen, we could be redirected to a screen explaining what is this ETSMobile, ... what do you think about that? If needed we could discuss this during the next meeting.

2021-03-22 02:39 UTC, apomalyn commented on lib/core/constants/router_paths.dart
> +  static const String chooseLanguage = "/choose-language";
```suggestion
  static const String chooseLanguage = "/discovery/choose-language";
```

2021-03-22 02:55 UTC, camillebrulotte commented
> Because this would probably be the first screen you see after your first login I think a popup isn't the best way to present this information. 
> 
> 
> 
> What do you think about a screen instead of a modal? After this screen, we could be redirected to a screen explaining what is this ETSMobile, ... what do you think about that? If needed we could discuss this during the next meeting.

2 weeks ago we discussed about it and stumbled upon the modal as a solution since the "full page" was reserved for "what's new". I think that's what I understood ? @AlexandreMarkus @emondhar @MysticFragilist 

But when I think about it again, a full page may be a better idea than the modal.

2021-03-22 13:03 UTC, AlexandreMarkus commented
Same as @camillebrulotte , but I think we should discuss it again

2021-03-22 23:14 UTC, camillebrulotte commented
Here are some ideas I came up with : 

[Choose_language.pdf](https://github.com/ApplETS/Notre-Dame/files/6185794/Choose_language.pdf)

Feel free if you have a better idea :D

2021-03-23 14:41 UTC, apomalyn commented
@camillebrulotte first of all, that was QUICK! :smile: 
I really like option A but there are some issues:

1. We can't use the French and UK flag because we are in Canada (and so use French Canadian and English Canadian), so we could remove the flags and turn the tiles in button (with card)
2. The light version of the screen should have a red background and a white logo to follow the theme of the previous and next screen.

What do you think ? :smile: (and by the way, great job :tada: )

2021-03-23 16:57 UTC, AlexandreMarkus commented
Same as @apomalyn I like option A

2021-03-24 01:12 UTC, MysticFragilist submitted a review, later dismissed

2021-03-24 01:15 UTC, MysticFragilist commented
Oups, just wanted to approve the changes I had prompted before. I didn't know it would approve the PR as a whole 😅

2021-03-24 12:39 UTC, camillebrulotte commented
Parff, option A it iss

2021-03-26 23:01 UTC, camillebrulotte commented
Voilà ! :D 

https://user-images.githubusercontent.com/37625944/112700903-92c29980-8e65-11eb-9658-17280b2bd110.mp4

https://user-images.githubusercontent.com/37625944/112700906-935b3000-8e65-11eb-8644-76001cd2b5ae.mp4

2021-03-30 06:03 UTC, apomalyn requested changes

2021-03-30 06:03 UTC, apomalyn commented on lib/core/viewmodels/startup_viewmodel.dart
> +import 'package:notredame/core/managers/settings_manager.dart';
Maybe we could merge these two sections? :thinking:

2021-04-01 01:48 UTC, apomalyn approved these changes
LGTM :1st_place_medal: :tada:

2021-04-01 02:22 UTC, merged