Feature/improve bug report feature
ApplETS/Notre-Dame pull request #708
Opened 2022-11-06 21:19 UTC by camillebrulotte

### ⁉️ Related Issue
**Will be merge after #703**, will change base branch after
closes #177 

## 📖 Description
*Change the ui of 'Report a bug'
* Add email in bottom sheet (optional'

### 🧪 How Has This Been Tested?

### ☑️ Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [x] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 
- [ ] Make sure golden files changes were reviewed and approved.

### 🖼️ Screenshots (if useful):
<img src="https://user-images.githubusercontent.com/37625944/200195572-0aaf2cb8-c0be-4b12-a7ae-86d998996682.png" width="300">

<img src="https://user-images.githubusercontent.com/37625944/200195578-75ee75af-4472-4092-b9c3-6b3a2d1baba4.png" width="300">

2022-11-06 22:00 UTC, AntoineLemelin approved these changes
LGTM

2022-11-11 17:01 UTC, Udito3 approved these changes
LGTM 😁

2023-01-15 17:43 UTC, Anthony-karabian commented
Very Nice @camillebrulotte

2023-01-20 21:57 UTC, eneiss requested changes
LGTM ! Juste une string à traduire si je me suis pas trompée :)
Good job en tout cas 🚀

2023-01-20 21:57 UTC, eneiss commented on l10n/intl_fr.arb
> +  "more_report_bug_step5": "sur le côté droit. \n\nEn mode navigation, vous pouvez naviguer librement dans l'application.\n\nPour passer en mode dessin, appuyez simplement sur le bouton 'Draw'. Vous
Est-ce que le bouton ne s'appellerait pas "Dessiner" au lieu de "Draw" quand l'app est en français ? En tout cas c'est comme ça que je comprends le fichier `lib/core/constants/custom_feedback_localization.dart`

2023-01-20 21:57 UTC, eneiss commented on lib/core/constants/custom_feedback_localization.dart
> +    const Locale('fr'): FrFeedbackLocalizations(),
Je suppose que non puisque tu as fait comme ça, mais est-ce que ces deux classes peuvent pas se factoriser en une seule qui prendrait en paramètre la locale, puis s'en servirait pour récupérer les strings depuis les fichiers `intl_[en|fr].arb` ?
Je vois pas trop ce qui empêche d'utiliser l'i18n habituel, tu peux m'éclaircir sur ce sujet stp @camillebrulotte ? 😄

2023-01-20 21:57 UTC, eneiss commented on lib/l10n/intl_en.arb
> +{}
Wut ? 🤔

2023-01-22 17:01 UTC, camillebrulotte commented on l10n/intl_fr.arb
> +  "more_report_bug_step5": "sur le côté droit. \n\nEn mode navigation, vous pouvez naviguer librement dans l'application.\n\nPour passer en mode dessin, appuyez simplement sur le bouton 'Draw'. Vous
True ! :D

2023-01-22 17:20 UTC, camillebrulotte commented on lib/core/constants/custom_feedback_localization.dart
> +    const Locale('fr'): FrFeedbackLocalizations(),
Avec la librairie de feedback on peut pas utiliser i18n dedans c'était pour ça :)

2023-01-22 22:59 UTC, eneiss commented on lib/core/constants/custom_feedback_localization.dart
> +    const Locale('fr'): FrFeedbackLocalizations(),
Ok je vois, merci ! 🙂

2023-01-22 23:02 UTC, eneiss submitted a review, later dismissed
LGTM 🔥

2023-01-29 19:07 UTC, Udito3 approved these changes
LGTM 😁

2023-01-29 21:53 UTC, eneiss approved these changes

2023-01-29 22:26 UTC, merged