Feature #277 Second way to exclude course activity of a specific group
ApplETS/Notre-Dame pull request #751
Opened 2023-01-15 14:34 UTC by Anthony-karabian

### ⁉️ Related Issue

## 📖 Description

### 🧪 How Has This Been Tested?

### ☑️ Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.
- [x] If needed, I added analytics.
- [x] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 
- [x] Make sure golden files changes were reviewed and approved.

### 🖼️ Screenshots (if useful):
Added new way to show and hide lab A and B :
![AddedNewMenuToDisplayGroup](https://user-images.githubusercontent.com/60085081/212546779-a0aaefe5-cbde-4b64-88fe-7c0f40dcfe8b.gif)

Removed the previous setting in the Schedule Settings:
![RemovedScheduleSettings](https://user-images.githubusercontent.com/60085081/212546812-eb51b898-35bd-41fa-9ae0-12170cd9441c.gif)

2023-01-22 22:58 UTC, camillebrulotte reviewed
Petits commentaires de import sinon très cool le feature ! :D 

Par contre je suis pas certaine de comprendre pourquoi on l'enlève aussi dans les settings ? 

Étant donné qu'on a pas d'indication que c'est clickable, c'est peut être pas évident pour les users de savoir qu'ils peuvent cliquer dessus vs tu scroll par hasard dans tes settings et tu tombes dessus. Donc ton feature est cool pour les personnes qui vont essayer de cliquer sur le cours mais pour quelqu'un qui y pense pas, celui dans les settings est plus accessible pour lui gooore ! Je sais pas si tu comprends ce que je veux dire haha ! 

Bref, je crois pas que ça causerait problème niveau ui/ux de pouvoir l'avoir à deux endroits, tu en penses quoi ? :D

2023-01-22 22:58 UTC, camillebrulotte commented on lib/core/managers/course_repository.dart
> +import 'package:ets_api_clients/exceptions.dart';
Devrait être dans // UTILS si je regarde comment les autres classes l'ont classé

2023-01-22 22:58 UTC, camillebrulotte commented on lib/core/managers/course_repository.dart
> +import 'package:ets_api_clients/clients.dart';
Devrait être dans // OTHER si je regarde comment les autres classes l'ont classé

2023-01-27 15:43 UTC, Anthony-karabian commented
> Petits commentaires de import sinon très cool le feature ! :D
> 
> Par contre je suis pas certaine de comprendre pourquoi on l'enlève aussi dans les settings ?
> 
> Étant donné qu'on a pas d'indication que c'est clickable, c'est peut être pas évident pour les users de savoir qu'ils peuvent cliquer dessus vs tu scroll par hasard dans tes settings et tu tombes dessus. Donc ton feature est cool pour les personnes qui vont essayer de cliquer sur le cours mais pour quelqu'un qui y pense pas, celui dans les settings est plus accessible pour lui gooore ! Je sais pas si tu comprends ce que je veux dire haha !
> 
> Bref, je crois pas que ça causerait problème niveau ui/ux de pouvoir l'avoir à deux endroits, tu en penses quoi ? :D

Oui je comprends tout a fait d'accord. Je vais remettre le feature dans le settings et régler les commentaires que t'as mis. Très apprécié de ton feedback. Merci

2023-01-29 02:52 UTC, Anthony-karabian commented on lib/core/managers/course_repository.dart
> +import 'package:ets_api_clients/exceptions.dart';
C'est corriger

2023-01-29 02:53 UTC, Anthony-karabian commented on lib/core/managers/course_repository.dart
> +import 'package:ets_api_clients/clients.dart';
c'est corrigé

2023-01-29 03:37 UTC, Anthony-karabian commented
J'ai rajouter la fonctionnalité dans le schedule settings

2023-01-29 03:51 UTC, XavierPaquet-Rapold requested changes

2023-01-29 03:51 UTC, XavierPaquet-Rapold commented on lib/core/viewmodels/schedule_viewmodel.dart
> +  }
Est-ce qu'il y aurait un moyen de découpler les méthodes du nom du labo appuyé ? L'objectif serait de permettre le cas d'utilisation de plus que 2 activités de lab.

2023-01-29 03:51 UTC, XavierPaquet-Rapold commented on lib/ui/views/dashboard_view.dart
> +            onLongPressedAction: () => {}),
Pourquoi pas mettre le `onLongPressedAction` en paramètre de constructeur optionnel ?

2023-01-29 03:51 UTC, XavierPaquet-Rapold commented on lib/ui/views/schedule_view.dart
> +              selectedTileColor: AppTheme.etsLightRed.withOpacity(0.5),
Si tu réussis à créer une seule méthode pour les trois ListTile, il serait possible de créer un builder de ListTyle en enlever ces trois bouts de code similaires.

2023-01-29 03:51 UTC, XavierPaquet-Rapold commented on lib/ui/widgets/course_activity_tile.dart
> +      {this.activity, this.onLongPressedAction, this.scheduleViewModel});
Voir si c'est possible de mettre `onLongPressedAction` optionnel.

2023-02-03 22:20 UTC, XavierPaquet-Rapold approved these changes
Just testing

2023-02-03 22:21 UTC, MysticFragilist approved these changes
test approve

2023-02-03 22:22 UTC, XavierPaquet-Rapold requested changes
Request changes after testing

2023-05-26 01:55 UTC, XavierPaquet-Rapold commented
I'll work on fixing the PR. I might start a new branch to do some maintenance on these widgets.

2023-09-07 20:59 UTC, closed without merging