Feature/forgot password link
ApplETS/Notre-Dame pull request #763
Opened 2023-02-03 15:38 UTC by J01716

### ⁉️ Related Issue

Closes: #736

## 📖 Description

Added text container at the bottom right of the password input in the login view.
Added method that opens URL received as parameter and call that method from the added text container with the link to the signets password change service : https://signets-ens.etsmtl.ca/Public/MotDePassePerdu.aspx

### 🧪 How Has This Been Tested?

The change was tested manually.

### ☑️ Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.
- [ ] If needed, I added analytics.
- [x] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 
- [ ] Make sure golden files changes were reviewed and approved.

### 🖼️ Screenshots (if useful):

![image](https://user-images.githubusercontent.com/60433475/216628585-eca818c4-71f3-478f-8e61-4fdae036d84d.png)
![image](https://user-images.githubusercontent.com/60433475/216632203-b3c51507-12bc-4d4f-895f-2559b5185c8a.png)
![image](https://user-images.githubusercontent.com/60433475/216632484-d5580b66-afa0-4e47-8a68-56fbfa7ad13d.png)

2023-02-03 16:59 UTC, eneiss submitted a review, later dismissed
LGTM, good job 🚀

2023-02-03 19:20 UTC, camillebrulotte reviewed
LGTM mais il semble avoir 3 tests qui ne passent plus sinon good job! :D https://github.com/ApplETS/Notre-Dame/actions/runs/4085632311/jobs/7043861447

2023-02-28 19:46 UTC, eneiss submitted a review, later dismissed
LGTM! Good job 🔥

2023-03-15 00:47 UTC, camillebrulotte submitted a review, later dismissed
Après le petit conflit, LGTM ! :D

2023-03-24 21:38 UTC, AntoineLemelin submitted a review, later dismissed
LGTM

2023-03-24 21:42 UTC, MysticFragilist approved these changes
LGTM! :fire:

2023-03-24 21:49 UTC, AntoineLemelin approved these changes
LGTM!

2023-03-24 21:51 UTC, XavierPaquet-Rapold requested changes

2023-03-24 21:51 UTC, XavierPaquet-Rapold commented on lib/ui/views/login_view.dart
> +  Future<void> launchInBrowser(String url) async {
Étant donné que c'est dupliqué d'un autre fichier, que penses-tu de créer un service `BrowserService` ?

2023-03-25 01:08 UTC, XavierPaquet-Rapold requested changes

2023-03-25 01:08 UTC, XavierPaquet-Rapold commented on lib/core/services/launch_url_in_browser_service.dart
> +// FLUTTER / DART / THIRD-PARTIES
Penses-tu qu'on pourrait l'ajouter dans la classe `LaunchUrlService` ?

2023-04-10 17:09 UTC, eneiss approved these changes
I noticed a hard-coded light theme in the safari viewer that could be improved, otherwise LGTM 💯

2023-09-07 13:53 UTC, camillebrulotte commented
Je vais reprendre cette PR

2023-09-07 18:54 UTC, camillebrulotte commented on lib/core/services/launch_url_service.dart
> +        preferredControlTintColor: AppTheme.lightThemeBackground,
Je vais regarder ça !

2023-09-09 16:13 UTC, Udito3 submitted a review, later dismissed
LGTM! :)

2023-09-09 16:21 UTC, JonathanDuvalV approved these changes
LGTM

2023-09-09 16:23 UTC, MysticFragilist requested changes

2023-09-09 16:23 UTC, MysticFragilist commented on lib/core/constants/urls.dart
> +  static const String signetsForgottenPword =
```suggestion
  static const String signetsForgottenPassword =
```

2023-09-09 16:25 UTC, JonathanDuvalV approved these changes

2023-09-09 16:25 UTC, MysticFragilist approved these changes
LGTM! :smile:

2023-09-09 16:27 UTC, Udito3 approved these changes
LGTM!

2023-09-09 17:03 UTC, merged