Replaced Rubik link with HorairÉTS link
ApplETS/Notre-Dame pull request #816
Opened 2023-05-26 06:16 UTC by gantanikhilraj

Closes Issue #807 

## 📖 Description
Replaced Rubik link with HorairÉTS link

2023-05-26 12:57 UTC, XavierPaquet-Rapold commented
@gantanikhilraj Thank you for your contribution to the project. I'll try to fix the worflow problem.

2023-05-26 13:35 UTC, HugoMigner commented on lib/core/constants/quick_links.dart
I would suggest to change the `intl.ets_schedule_generator` string in `l10n/intl_en.arb` and `l10n/intl_fr.arb` to a more fitting title, since we are changing the link from Rubik to HoraireÉTS

2023-05-26 13:35 UTC, HugoMigner requested changes
@gantanikhilraj Thank you for your contribution! I would suggest a simple change, since the quick link card isn't going to represent Rubik anymore.

2023-05-28 21:39 UTC, MysticFragilist commented
Hi! Hey thanks for your contribution @gantanikhilraj 😄Small comment on this, are you guys sure we should replace it entirely? I would be more inclined to just add a new link since I think Rubik is still actively maintain. Maybe an idea would be to just add a parameter for schedule generator in general settings to toggle rubik on and off and put rubik as the default. We still don't know if horairETS will be supported in the future since it's still on a personal link and it's not actually open-source for now.

2023-07-02 04:04 UTC, MysticFragilist commented
> Hi! Hey thanks for your contribution @gantanikhilraj 😄Small comment on this, are you guys sure we should replace it entirely? I would be more inclined to just add a new link since I think Rubik is still actively maintain. Maybe an idea would be to just add a parameter for schedule generator in general settings to toggle rubik on and off and put rubik as the default. We still don't know if horairETS will be supported in the future since it's still on a personal link and it's not actually open-source for now.

Nevermind my other comment, since yesterday Rubiks team announced that they removed their rubiks implementation to make place for horairÉTS so all is good with this PR! There is just the small ajustment for the name of the link to change as @HugoMigner  mentionned remaining!  Keep it up 😄

2023-07-16 19:30 UTC, MysticFragilist commented
@gantanikhilraj are you still looking into this? if not, I'll close this PR and unassign this issue

2023-07-24 21:25 UTC, MysticFragilist commented
Closing this! since there is no activity 😄

2023-07-24 21:25 UTC, closed without merging