Feature/month view calendar
ApplETS/Notre-Dame pull request #842
Opened 2023-09-12 21:05 UTC by DavidMartel12

## 📖 Description
I added the monthly view to the new calendar view.

### 🧪 How Has This Been Tested?
Existing tests have been modified to implement the new information required for the calendar view.

### ☑️ Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.
- [x] If needed, I added analytics.
- [x] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 
- [x] Make sure golden files changes were reviewed and approved.

### 🖼️ Screenshots (if useful):
![Screenshot_1694552060](https://github.com/ApplETS/Notre-Dame/assets/92378108/1da2e5fe-3ce7-4843-973f-a8b51112ed1d)

2023-09-14 16:53 UTC, camillebrulotte requested changes

2023-09-14 16:53 UTC, camillebrulotte commented on lib/core/viewmodels/schedule_viewmodel.dart
> +    for (int i = 0; i < 42; i++) {
Peut-être mettre le 42 dans une constante pour savoir ça représente quoi ? :D

2023-09-16 23:42 UTC, XavierPaquet-Rapold commented on lib/ui/views/schedule_view.dart
> +      return Scaffold(
Est-ce qu'on pourrait mettre ce Scaffold dans une classe différente pour que ce soit plus un Component ?

2023-09-22 03:00 UTC, XavierPaquet-Rapold approved these changes
LGTM après l'update du pubspec

2023-09-22 13:25 UTC, camillebrulotte approved these changes
LGTM !

2023-09-27 18:38 UTC, XavierPaquet-Rapold submitted a review, later dismissed

2023-11-01 15:40 UTC, clubapplets-server submitted a review, later dismissed
LGTM! -Sam

2023-11-09 21:07 UTC, MysticFragilist submitted a review, later dismissed

2023-11-10 04:22 UTC, XavierPaquet-Rapold submitted a review, later dismissed

2023-11-10 04:48 UTC, XavierPaquet-Rapold approved these changes

2023-11-14 21:57 UTC, camillebrulotte approved these changes
LGTM !

2023-11-14 23:47 UTC, merged