Change launch url logic to webview
ApplETS/Notre-Dame pull request #889
Opened 2023-11-14 20:08 UTC by HugoMigner

## 📖 Description
On Android, the broadcast card, when type = link, launched a native webview with limited controls. The webview has been changed to the already integrated one in the app.

### ☑️ Checklist before requesting a review
- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] If needed, I added analytics.
- [ ] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 
- [ ] Make sure golden files changes were reviewed and approved.

2023-11-14 20:20 UTC, MysticFragilist requested changes

2023-11-14 20:20 UTC, MysticFragilist commented on lib/ui/views/dashboard_view.dart
> -            Utils.launchURL(url, AppIntl.of(context));
Tant qu'à y être, peut-être rajouter `@Deprecated('<reason>')` ou si ce n,est pas utiliser ailleurs tout simplement retirer la fonction Utils.launchURL pour éviter les problèmes futurs!

2023-11-15 00:19 UTC, HugoMigner commented on lib/ui/views/dashboard_view.dart
> -            Utils.launchURL(url, AppIntl.of(context));
Je viens de faire le tour du code un peu, et la méthode `Utils.launchURL()` est utilisée pour lancer des liens qui peuvent rediriger vers une application (les icônes dans la carte App|ETS dans le dashboard, Facebook, GitHub, Email, etc), tandis que les méthodes utilisées dans cette PR sont plus pour les webviews! Donc dans mon cas je pense que j'utilise la bonne méthode, et pas besoin d'apporter des modifs à `Utils.launchURL()`!

2023-11-16 04:51 UTC, XavierPaquet-Rapold submitted a review, later dismissed
LGTM 🔥

2023-11-16 15:45 UTC, MysticFragilist approved these changes
LGTM!

2023-11-16 18:13 UTC, MysticFragilist approved these changes

2023-11-16 18:14 UTC, merged