Fix quicklinks landscape mode
ApplETS/Notre-Dame pull request #893
Opened 2023-11-16 15:22 UTC by LouisPhilippeHeon

Closes: https://github.com/ApplETS/Notre-Dame/issues/880

## 📖 Description
En mode paysage 6 quicklinks s'affichent sur la largeur, ça évite de devoir scroller.
Les FaIcons des quicklinks sont désormais responsive, donc si à l'avenir on veut changer leur taille c'est possible.

### 🧪 How Has This Been Tested?
Je n'ai pas écrit de tests, mais si quelqu'un pense que c'est pertinent je peux en ajouter. Testé sur Android, en paysage et portrait.

### ☑️ Checklist before requesting a review
- [X] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] If needed, I added analytics.
- [X] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 
- [ ] Make sure golden files changes were reviewed and approved.

### 🖼️ Screenshots (if useful):
<img width="1138" alt="Capture d’écran, le 2023-11-16 à 10 17 37" src="https://github.com/ApplETS/Notre-Dame/assets/83369199/cabd3d66-1ffa-4d98-bc2c-cba300a90645">

2023-11-16 15:31 UTC, mataai commented on lib/ui/views/quick_links_view.dart
> +          (MediaQuery.of(context).orientation == Orientation.portrait) ? 3 : 6,
Ça serait cool qu'on calcule selon la largeur de l'écran plutot que de hardcodé un nombre spécifique de tuiles. Sur mon cell elle sont vraiment stretched. mais ça serait juste un QOL update rien de breaking dans la pr

2023-11-16 15:39 UTC, LouisPhilippeHeon commented on lib/ui/views/quick_links_view.dart
> +          (MediaQuery.of(context).orientation == Orientation.portrait) ? 3 : 6,
Ouain, je pourrais diviser la taille de l'écran par une taille idéale pour une tuile pour calculer combien de liens peuvent "fitter" en largeur... Je vais faire ce changement là tantôt.

2023-11-16 15:49 UTC, MysticFragilist approved these changes
Mise à part le commentaire de Matei, LGTM pour moi! GG 💯

2023-11-16 16:06 UTC, mataai commented
LGTM

2023-11-16 19:28 UTC, XavierPaquet-Rapold requested changes

2023-11-16 19:28 UTC, XavierPaquet-Rapold commented on lib/ui/views/quick_links_view.dart
> +      crossAxisCount: ((MediaQuery.of(context).size.width) / 100).floor(),
Peut-être revoir ça, dans le golden, on voit qu'il y a deux cartes par ligne. Ça fait que les cartes sont très grandes. Peut-être mettre `ceil()` ?

2023-11-16 19:47 UTC, LouisPhilippeHeon commented on lib/ui/views/quick_links_view.dart
> +      crossAxisCount: ((MediaQuery.of(context).size.width) / 100).floor(),
Si je fais .ceil() sur mon émulateur les tuiles sont plus petite que auparavant. Avec .floor() j'en affiche déjà 3 colonnes sur un petit téléphone comme un nexus one 3.7".

2023-11-16 21:40 UTC, MysticFragilist commented on lib/ui/views/quick_links_view.dart
> +      crossAxisCount: ((MediaQuery.of(context).size.width) / 100).floor(),
Ça fait du sens qu'il y ait que 2 colonnes sur le golden je crois, l'appareil du golden est vraiment petit (comme si c'est un mini cellulaire), le but étant d'identifier s'il y a des overflows à travers l'application. Le Width/Height du golden:
<img width="154" alt="image" src="https://github.com/ApplETS/Notre-Dame/assets/25663435/d7101de9-b088-4da5-8ed5-5e94c97c17d3">

Donc c'est cool ça prouve que si jamais on aurait un mini screen ou un très vieux cell ça serait juste sur 2 colonnes!

2023-11-16 21:41 UTC, MysticFragilist commented on lib/ui/views/quick_links_view.dart
> +      crossAxisCount: ((MediaQuery.of(context).size.width) / 100).floor(),
je pense à ça, @LouisPhilippeHeon t'as essayer sur ton nexus 2 de reorder les cartes? ça fonctionne tu toujours?

2023-11-16 22:00 UTC, LouisPhilippeHeon commented on lib/ui/views/quick_links_view.dart
> +      crossAxisCount: ((MediaQuery.of(context).size.width) / 100).floor(),
Oui ça fonctionne

2023-11-17 01:25 UTC, XavierPaquet-Rapold commented on lib/ui/views/quick_links_view.dart
> +      crossAxisCount: ((MediaQuery.of(context).size.width) / 100).floor(),
Sur un Pixel6, c'est rendu 4 petites cartes: 
![image](https://github.com/ApplETS/Notre-Dame/assets/80051842/a1e3cad7-1045-4dd1-a6b4-ae37ad3853d8)

2023-11-17 01:38 UTC, LouisPhilippeHeon commented on lib/ui/views/quick_links_view.dart
> +      crossAxisCount: ((MediaQuery.of(context).size.width) / 100).floor(),
Avec 120 au lieu de 100 ça le ramènerais probablement à 3 colonnes.

2023-11-17 16:34 UTC, LouisPhilippeHeon commented on lib/ui/views/quick_links_view.dart
> +      crossAxisCount: ((MediaQuery.of(context).size.width) / 100).floor(),
Je viens de tester, sur mon petit téléphone si je met plus que 106, ça affiche juste 2 colonnes. 

J'ai l'impression que il y a pas de valeur "juste" qui aura l'air parfait sur tous les appareils. J'ai fait des recherches et les téléphones (pas fold) les plus gros qui sont populaires ont un viewport moins de 430. 

Donc pour afficher 3 colonnes sur ces gros téléphones, il faudrait que la largeur cible d'une tuile soit de plus de 107,5, donc 110 serait probablement idéal. 

Sur les téléphones minuscules ayant un viewport de 330 ou moins ça ferait juste 2 colonnes, on aurait juste 2 colonnes. Pour donner un ordre d'idée, un iPhone SE a un viewport de 320. C'est pas une taille très populaire mais ce serait dommage que ceux qui en ont aient des tuiles gigantesques.

Donc plusieurs possibilités s'offrent à nous :
 - Ceux qui ont des petits téléphones ont des grosses tuiles mais c'est bien affiché sur le reste des appareils.
 - Ceux qui ont des gros téléphones ont des tuiles trop petites.
 - On complique le calcul de la colonne et on défini des valeurs entre lesquels il doit y avoir 3 colonnes, et au delà/en dessous de ces valeurs, on fait une division par 110 pour le nombre de colonnes.

2023-11-20 05:26 UTC, XavierPaquet-Rapold commented on lib/ui/views/quick_links_view.dart
> +      crossAxisCount: ((MediaQuery.of(context).size.width) / 100).floor(),
En voyant les 10 téléphones sur lesquels l'application est le plus utilisé, on peut se dire que les utilisateurs on tendance à utiliser de plus gros appareils.

![image](https://github.com/ApplETS/Notre-Dame/assets/80051842/155ef92f-dcb7-4dff-9716-da5d5b93a645)

Ainsi, j'ai tendance à dire que les plus petits appareils devraient avoir des plus gros icones et les plus gros devraient rester à 3 colonnes comme actuellement

2023-11-20 05:33 UTC, XavierPaquet-Rapold commented on lib/ui/views/quick_links_view.dart
> +      crossAxisCount: ((MediaQuery.of(context).size.width) / 100).floor(),
On pourrait aussi jouer mettre une taille max des cartes et si cette taille est dépassée, ce serait la distance entre les cartes qui augmente. Je ne sais pas vraiment si ça se fait en Flutter

2023-11-20 05:43 UTC, LouisPhilippeHeon commented on lib/ui/views/quick_links_view.dart
> +      crossAxisCount: ((MediaQuery.of(context).size.width) / 100).floor(),
Comme j'ai dit dans mon message juste avant, les petits téléphones sont peu populaires, mais je pense juste que ce serait plate de les négliger le peu d'effort requis pour que ça s'affiche bien peut importe la taille.

Genre on pourrait faire ça pour que ça soit parfait pour tout le monde :
``` dart
getNumberOfColumns() {
  if (largeur > 320 && largeur < 430)
    return 3;
  else 
    return largeur/110.floor();
}
```

2023-11-20 14:34 UTC, XavierPaquet-Rapold commented on lib/ui/views/quick_links_view.dart
> +      crossAxisCount: ((MediaQuery.of(context).size.width) / 100).floor(),
Cet algorithme là semble correct, fait juste mettre un minimum de 1 colonne

2023-11-21 15:32 UTC, LouisPhilippeHeon commented on lib/ui/views/quick_links_view.dart
> +      crossAxisCount: ((MediaQuery.of(context).size.width) / 100).floor(),
Je vais rajouter .clamp(1, double.infinity).toInt().

2023-11-21 16:02 UTC, LouisPhilippeHeon commented on lib/ui/views/quick_links_view.dart
> +      crossAxisCount: ((MediaQuery.of(context).size.width) / 100).floor(),
J'ai légèrement changé les valeurs de la méthode que j'avais suggéré après avoir fait des essais dans des simulateurs, maintenant tout a l'air correct.

2023-11-21 16:33 UTC, XavierPaquet-Rapold approved these changes
LGTM 🔥

2023-11-21 17:13 UTC, merged