Allow resizing schedule settings
ApplETS/Notre-Dame pull request #899
Opened 2023-11-24 00:37 UTC by LouisPhilippeHeon

Closes https://github.com/ApplETS/Notre-Dame/issues/896

## 📖 Description

Upon scrolling in the list of settings, it will expand.

### 🧪 How Has This Been Tested?
Tested on android and iOS, both with light and dark mode.

### ☑️ Checklist before requesting a review
- [X] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] If needed, I added analytics.
- [X] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 
- [ ] Make sure golden files changes were reviewed and approved.

### 🖼️ Screenshots (if useful):
<img width="367" alt="Capture d’écran, le 2023-11-23 à 16 21 51" src="https://github.com/ApplETS/Notre-Dame/assets/83369199/f7011130-aaea-42fd-a4e2-cfcbb6916528">

2023-11-30 18:31 UTC, MysticFragilist requested changes
Petit test à ajouter sinon tout est vraiment bien! 😄 Good job!

2023-11-30 18:31 UTC, MysticFragilist commented on lib/ui/widgets/schedule_settings.dart
> +                builder: (context, ScrollController scrollController) {
Si jamais t'es capable de faire un petit test, pour vérifier si ça a snap en haut ou pas, ça serait cool! Tu peux t'inspirer des widget tests existants sinon aller voir la doc sur flutter c'est assez bien documenter!! Tu peux faire ces opérations là dans le test:
- Drag vers le haut;
- Vérifier que le child size à snap à la taille voulu.
Devrait pas être trop compliqué, mais si tu as des questions fais-moi signe! :)

2024-03-20 23:35 UTC, XavierPaquet-Rapold approved these changes

2024-03-21 01:40 UTC, MysticFragilist approved these changes
LGTM!

2024-03-21 01:51 UTC, merged