Fix repeated colors in schedule cards
ApplETS/Notre-Dame pull request #907
Opened 2023-12-05 20:31 UTC by HugoMigner

### ⁉️ Related Issue
When the schedule has more than 1 session worth of classes, we can start seeing repeated colors on the background of certain cards.

## 📖 Description
Change the colors in the schedule cards palette.

2023-12-05 21:36 UTC, MysticFragilist requested changes
Petite interrogation sinon Good job 😄

2023-12-05 21:36 UTC, MysticFragilist commented on lib/ui/utils/app_theme.dart
> +    Color(0xffe74c3c),
ahh je pensais c'était déjà fait, mais on aimerait pas utiliser la paletteLight si il est en Light et la paletteDark s'il est en dark au lieu d'enlever la dark? À mon souvenir on avait générés deux teintes de la même couleur pour que ça match mieux avec chacun des thèmes... Ça serait cool de faire ça comme ça, t'en pense quoi?

2023-12-08 14:17 UTC, HugoMigner commented on lib/ui/utils/app_theme.dart
> +    Color(0xffe74c3c),
C'est arrangé :) Je rajoute des screenshots avec les 2 palettes!

2023-12-08 15:08 UTC, JonathanDuvalV submitted a review, later dismissed

2024-04-12 00:51 UTC, XavierPaquet-Rapold approved these changes
Bon, je sais que j'ai aidé dans la PR, mais LGTM

2024-04-12 01:18 UTC, mataai commented on lib/ui/utils/app_theme.dart
> +    Color(0xffe74c3c),
Ça me semble être resolved?

2024-04-12 01:21 UTC, merged

2024-04-12 04:33 UTC, HugoMigner commented on lib/ui/utils/app_theme.dart
> +    Color(0xffe74c3c),
Oui fixed!