Fix schedule cards not showing the correct end time
ApplETS/Notre-Dame pull request #908
Opened 2023-12-06 20:51 UTC by HugoMigner

### ⁉️ Related Issue
Closes #902 

## 📖 Description
Changed the logic in the end time formatting to correctly show the end time.

### ☑️ Checklist before requesting a review
- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] If needed, I added analytics.
- [ ] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 
- [ ] Make sure golden files changes were reviewed and approved.

2023-12-06 21:02 UTC, MysticFragilist requested changes
Petit interrogation sur le formattage de dates, sinon all good j'avais pas remarquer le bogue good job!! :smile:

2023-12-06 21:02 UTC, MysticFragilist commented on lib/ui/widgets/schedule_calendar_tile.dart
> +    }
Quelque chose comme ça serait pt plus clean pour formatter les dates t'en penses quoi?

```suggestion
    final DateFormat formatter = DateFormat('H:m');
    final String formatted = formatter.format(widget.end.add(const Duration(minutes: 1)));
    var endTime = formatted;
```

2023-12-08 14:29 UTC, HugoMigner commented on lib/ui/widgets/schedule_calendar_tile.dart
> +    }
J'ai changé le formatting de endTime pour quelque chose qui ressemble à ça, laisse moi savoir ce que t'en penses :)

2023-12-31 03:34 UTC, camillebrulotte submitted a review, later dismissed
LGTM !

2024-04-12 05:29 UTC, MysticFragilist requested changes

2024-04-12 05:29 UTC, MysticFragilist commented on lib/ui/widgets/schedule_calendar_tile.dart
> +        : "${widget.start?.hour}:${widget.start?.minute.toString().padLeft(2, '0')}";
ça je sais pas exactement comment ça marche en flutter, mais on peut pas forcer qu'on connait que la variable sera pas null dans le ternary?
```suggestion
        : "${widget.start!.hour}:${widget.start!.minute.toString().padLeft(2, '0')}";
```

2024-04-12 13:42 UTC, MysticFragilist submitted a review, later dismissed

2024-05-08 22:48 UTC, merged