Add weighted grade in evaluation tile
ApplETS/Notre-Dame pull request #921
Opened 2024-01-26 02:52 UTC by DylanApardian

### ⁉️ Related Issue
Closes https://github.com/ApplETS/Notre-Dame/issues/910

## 📖 Description
Added weighted grade in evaluation tile. 

For example, a grade of 73.0/95 on an exam worth 20%.
The weighted grade would be 15.3/20. 

In reality, the correct weighted grade would be 15.36 but I decided to truncate to the first decimal for consistency.

I noticed a discrepancy in grades when using `toStringAsFixed(1)` to calculate the weighted grade since this extension method rounds the number.
For example, a grade of 26.0/30 on an exam worth 10%. The grade would be 86.7% and when using `toStringAsFixed(1)` to calculate the weighted grade, we get 8.7/10. 

This would look weird to the user. Which is why I decided to create a `truncateDecimalPlaces()` helper method that essentially does the same thing as `toStringAsFixed(1)` without rounding. Using this new helper method we get 8.6/10 as the weighted grade,  which looks more like 86.7%.

### 🧪 How Has This Been Tested?
Tested manually and added a unit test.

### ☑️ Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.
- [ ] If needed, I added analytics.
- [x] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 
- [x] Make sure golden files changes were reviewed and approved.

### 🖼️ Screenshots (if useful):
![screenshot_1](https://github.com/ApplETS/Notre-Dame/assets/155918717/3e7c82a6-f639-456d-a5bf-3125945fe264)
![screenshot_2](https://github.com/ApplETS/Notre-Dame/assets/155918717/9b11804f-d511-4735-8af5-f5c05b1364da)

2024-01-30 22:38 UTC, MysticFragilist requested changes
Petit commentaire sinon tout à l'air beau!

2024-01-30 22:38 UTC, MysticFragilist commented on lib/ui/widgets/grade_evaluation_tile.dart
> +    return Utils.truncateDecimalPlaces((grade / outOf) * weight, 1);
pour ici, je pense tu pourrais simplement utiliser une fonction pour convertir le double en string avec un nombre de de décimale: `toStringAsFixed(2)` -> https://api.flutter.dev/flutter/dart-core/num/toStringAsFixed.html

2024-01-30 23:19 UTC, DylanApardian commented on lib/ui/widgets/grade_evaluation_tile.dart
> +    return Utils.truncateDecimalPlaces((grade / outOf) * weight, 1);
Je suis d'accord avec toi. En effet, c'est ce que j'avais fait au début. 

J'ai constaté que les autres notes (grade, average, median) avaient seulement 1 chiffre décimal de précision. Je voulais rester "consistent" avec les autres valeurs.

Si c'est correct avec toi d'utiliser une précision de décimales de 2 chiffres ici, alors je vais utiliser `toStringAsFixed(2)`.

2024-02-14 13:45 UTC, MysticFragilist submitted a review, later dismissed
LGTM! :100:

2024-03-05 02:48 UTC, EffBureau submitted a review, later dismissed
LGTM ✅

2024-03-28 00:21 UTC, XavierPaquet-Rapold requested changes

2024-03-28 00:21 UTC, XavierPaquet-Rapold commented on lib/ui/widgets/grade_evaluation_tile.dart
> +  }
Est-ce que ce serait possible de créer une classe d'extension de CourseEvaluation qui calcule le weighted grade ? Ou faire un ViewModel qui le fait ? L'objectif serait de séparer la logique d'affaire du UI

2024-03-28 17:25 UTC, DylanApardian commented on lib/ui/widgets/grade_evaluation_tile.dart
> +  }
Si j'ajoute un nouveau property `weightedGrade` dans `course_evaluation`, tu penses que ce serait correct?

2024-03-28 19:11 UTC, DylanApardian commented on lib/ui/widgets/grade_evaluation_tile.dart
> +  }
Je pense qu'il serait préférable d'avoir un property `weightedGrade` faisant partie de `course_evaluation`. @MysticFragilist j'ai parlé avec Xavier et il pense qu'on devrait parler avec toi avant de prendre une decision.

Qu'en penses-tu ?

2024-04-12 01:50 UTC, XavierPaquet-Rapold approved these changes
LGTM 🔥

2024-04-12 13:17 UTC, XavierPaquet-Rapold submitted a review, later dismissed

2024-04-12 13:24 UTC, MysticFragilist commented on lib/ui/widgets/grade_evaluation_tile.dart
> +  }
ahh merde j'avais pas vu le commentaire sur la PR et en vrai @DylanApardian ça a du sens de mettre une property autocomputed sur la classe dans le client de course_evaluation. 

La seule chose que je ne suis pas sûr, c'est comme c'est un package client je voulais à la base rajouter le moins de calcul dedans, et juste avoir les retours des endpoints le plus raw possible. 

Ça reste du calcul assez rudimentaire qui est en lien avec les données retournées, donc peut-être, mais je pense ça reste valide de le laisser ici aussi selon moi, j'ai pas trop de préférences!

2024-05-11 20:29 UTC, merged