Hello - Author view
ApplETS/Notre-Dame pull request #933
Opened 2024-02-26 02:55 UTC by Udito3

### ⁉️ Related Issue
Tâche Jira

## 📖 Description

- Ajout de la page d'auteur de nouvelles
- Navigation jusqu'à la page
- Ajout d'héro pour l'animation entre les pages

### 🧪 How Has This Been Tested?
- Des tests ont été fait pour tout les nouveaux fichiers

### ☑️ Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.
- [x] If needed, I added analytics.
- [x] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 
- [x] Make sure golden files changes were reviewed and approved.

### 🖼️ Screenshots (if useful):
<img src="https://github.com/ApplETS/Notre-Dame/assets/47289926/7c97b9c6-8108-4310-929e-157eaea1a275" alt="image" width="200">
<img src="https://github.com/ApplETS/Notre-Dame/assets/47289926/000d4830-4904-4341-b287-49c979af0962" alt="image" width="200">
<img src="https://github.com/ApplETS/Notre-Dame/assets/47289926/a2ec46b2-31c3-4a8f-91de-65c25df79b74" alt="image" width="200">
<img src="https://github.com/ApplETS/Notre-Dame/assets/47289926/7dd726d2-610a-44a9-ad32-d118b2001da1" alt="image" width="200">
<img src="https://github.com/ApplETS/Notre-Dame/assets/47289926/0ce39784-0805-4bcf-afec-270ce9f325f9" alt="image" width="200">
<img src="https://github.com/ApplETS/Notre-Dame/assets/47289926/290372de-5022-4404-b872-7323f053a2ea" alt="image" width="200">

2024-02-26 15:42 UTC, MysticFragilist requested changes

2024-02-26 15:42 UTC, MysticFragilist commented on lib/core/managers/news_repository.dart
> +  // TODO : Fetch news from the API
```suggestion
  // TODO : Fetch news from the API
```

2024-02-26 15:42 UTC, MysticFragilist commented on lib/ui/widgets/social_links_card.dart
> +                child: Column(
Peut-être les boutons ne rentrerons pas si c'est un petit écran (comme discuté) Peut-être essayer avec une scroll view dans le cas où c'est un petit écran. Le mieux serait de faire fit le drawer avec la grosseur des icons au lieu de le fixer à 30% du size total.

2024-02-26 15:51 UTC, MysticFragilist requested changes

2024-03-24 05:59 UTC, MysticFragilist requested changes
petite question sinon c'est good!

2024-03-24 05:59 UTC, MysticFragilist commented on lib/core/viewmodels/author_viewmodel.dart
> +    isNotified = !isNotified;
Faudrait pas avoir une petite logique pour sauvegarder dans le cache pour pas que across les loading de la page ça se fasse revert? ou le TODO c'tait ça? Si c'était le TODO faudrait juste être sûr il y a une tâche dans Jira pour ça!

Actually, le notify me on pourra en reparler avec tout le monde, je ne suis pas sûr on aura le temps

2024-03-25 00:20 UTC, Udito3 commented on lib/core/viewmodels/author_viewmodel.dart
> +    isNotified = !isNotified;
Ouais mettons que c'était un gros TODO de "je sais même pas si on va le faire fait que je vais pas mettre trop de temps là dessus" hahahaha
Mais je vais créer une tache pour s'il y en a pas et on verra si on le fait

2024-03-25 05:36 UTC, MysticFragilist approved these changes
LGTM!

2024-03-25 15:35 UTC, merged