Feature/68 migration to null safety
ApplETS/Notre-Dame pull request #939
Opened 2024-03-09 03:29 UTC by XavierPaquet-Rapold

### ⁉️ Related Issue
Closes #68 
Null safety

## 📖 Description
Migrate to null safety

### 🧪 How Has This Been Tested?
Everything was tested

### ☑️ Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.
- [x] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 
- [x] Make sure golden files changes were reviewed and approved.

2024-03-09 05:53 UTC, XavierPaquet-Rapold commented on test/ui/views/goldenFiles/gradesDetailsView_2.png
Voir pourquoi la view affiche la page d'erreur. grades_details_view_test ligne 236

2024-03-09 05:54 UTC, XavierPaquet-Rapold commented on test/ui/views/goldenFiles/gradesDetailsView_evaluation_not_completed.png
Même ici

2024-03-10 01:15 UTC, XavierPaquet-Rapold commented on test/ui/views/goldenFiles/gradesDetailsView_2.png
Finalement, c'est parce que le test affiche la page de "no grades available" ce qui est normal, comme le test est: "if there is no grades available"

2024-03-10 01:19 UTC, XavierPaquet-Rapold commented on test/ui/views/goldenFiles/gradesDetailsView_evaluation_not_completed.png
Finalement, c'est parce que le test affiche la page de "Evaluation Not Completed" ce qui est normal, comme le test est: "if in the evaluation period and evaluation not completed"

2024-03-10 01:42 UTC, MysticFragilist approved these changes
LGTM! Good job Xavier, t'as bien fait ça, null safety nous voilà!!!😄 Merci à @apomalyn pour l'aide aussi!

2024-03-10 20:51 UTC, Udito3 submitted a review, later dismissed
LGTM! Good job!!!! 😁

2024-03-11 14:40 UTC, MysticFragilist requested changes

2024-03-11 14:40 UTC, MysticFragilist commented on lib/core/viewmodels/more_viewmodel.dart
> +    }
ici on est sûr que ça marche? le _appVersion se fait jamais set

2024-03-11 18:47 UTC, XavierPaquet-Rapold commented on lib/core/viewmodels/more_viewmodel.dart
> +    }
Oh bon catch !

2024-03-13 03:34 UTC, MysticFragilist commented on lib/ui/views/dashboard_view.dart
> +      throw Exception("Cards is null");
Est-ce que ça serait worth de mettre un analytics au cas où quand même?

2024-03-13 03:48 UTC, MysticFragilist submitted a review, later dismissed
Autres que la question en haut LGTM! 😄

2024-03-13 03:50 UTC, XavierPaquet-Rapold commented on lib/ui/views/dashboard_view.dart
> +      throw Exception("Cards is null");
Done

2024-03-13 03:54 UTC, XavierPaquet-Rapold commented on lib/core/managers/user_repository.dart
> +        throw const ApiException(prefix: tag, message: "Not authenticated");
Log l'erreur

2024-03-13 03:56 UTC, XavierPaquet-Rapold commented on lib/core/services/navigation_service.dart
> +      return Future.error("Navigator state is null");
Log

2024-03-13 03:56 UTC, XavierPaquet-Rapold commented on lib/core/services/navigation_service.dart
> +      return Future.error("Navigator state is null");
Log

2024-03-13 04:00 UTC, XavierPaquet-Rapold commented on lib/core/viewmodels/grades_details_viewmodel.dart
> +      onError(e);
Log dans onError ?

2024-03-13 04:01 UTC, XavierPaquet-Rapold commented on lib/core/viewmodels/grades_viewmodel.dart
> +      onError(error);
Log ?

2024-03-14 02:55 UTC, merged