Hello/master
ApplETS/Notre-Dame pull request #981
Opened 2024-05-12 23:29 UTC by XavierPaquet-Rapold

## 📖 Description
Hello project

### 🧪 How Has This Been Tested?
Just to check the changes

### ☑️ Checklist before requesting a review
- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] If needed, I added analytics.
- [ ] Make sure to add either one of the following labels: `version: Major`,`version: Minor` or `version: Patch`. 
- [ ] Make sure golden files changes were reviewed and approved.

### 🖼️ Screenshots (if useful):

2024-05-13 21:24 UTC, mataai approved these changes

2024-05-13 21:24 UTC, mataai commented on lib/ui/views/author_view.dart
> +        SocialLink(id: 7, name: 'LinkedIn', link: author!.linkedInLink!),
Pourquoi ya tant de non nullable? ☠️

2024-05-16 00:55 UTC, XavierPaquet-Rapold commented on lib/ui/views/news_details_view.dart
> +            "https://hello.montydev.ca/fr/dashboard/news?id=${news.id}");
Mettre dans constante

2024-06-01 16:19 UTC, MysticFragilist requested changes
Je laisse ça pour l'instant je continue de regarder ça en après-midi!

2024-06-01 16:19 UTC, MysticFragilist commented on .github/workflows/release-workflow.yaml
> +          flutter-version: '3.x'
dans master-workflow, il est set à 3.19.x, perso j'aimes bien quand c'est fix à une minor pour éviter des problèmes de build. Exemple, quand ça à bloquer à 3.3.x ça éviter qu'il tente de build le projet sur 3.19.x alors qu'on avait pas nullable d'instaurer. Normalement, les breaking changes sont supposé être uniquement sur les majors, mais on dirait que google respecte pas toujours ça.

Mais ça ne me dérange pas non plus de rouler sur la rolling minor tant que le master-workflow est aussi sur la même version!

2024-06-01 16:19 UTC, MysticFragilist commented on l10n/intl_en.arb
> +  "report_inappropriate_content_description": "Ad containing hate speech, shocking images, or adult content.",
Peut-être plus ça?
```suggestion
  "report_inappropriate_content_description": "News containing hate speech, shocking images, or adult content.",
```

2024-06-01 16:19 UTC, MysticFragilist commented on l10n/intl_en.arb
> +  "report_false_information_description": "Ad that appears to be false or misleading.",
```suggestion
  "report_false_information_description": "News that appears to be false or misleading.",
```

2024-06-01 16:19 UTC, MysticFragilist commented on l10n/intl_en.arb
> +  "report_harassment_or_abuse_description": "Ad targeting a person or group in an abusive manner.",
```suggestion
  "report_harassment_or_abuse_description": "News targeting a person or group in an abusive manner.",
```

2024-06-01 16:19 UTC, MysticFragilist commented on l10n/intl_en.arb
> +  "report_outdated_content_description": "Ad that is no longer up-to-date or relevant.",
```suggestion
  "report_outdated_content_description": "News that is no longer up-to-date or relevant.",
```

2024-06-01 16:19 UTC, MysticFragilist commented on l10n/intl_fr.arb
> +  "news_export_success": "L'événement a été exporté avec succès",
En français, je sais pas si on devrait dire annonce partout ou évènement partout? comme tu le sens j'ai pas de préférences, mais faudrait ça soit tout pareil.

My bad j'aivais pas vu ça pendant les reviews de notre projet 😅 
```suggestion
  "news_export_success": "L'annonce a été exporté avec succès",
```

2024-06-01 16:26 UTC, XavierPaquet-Rapold commented on lib/ui/views/author_view.dart
> +        SocialLink(id: 7, name: 'LinkedIn', link: author!.linkedInLink!),
Done

2024-06-01 16:26 UTC, XavierPaquet-Rapold commented on l10n/intl_en.arb
> +  "report_inappropriate_content_description": "Ad containing hate speech, shocking images, or adult content.",
Done

2024-06-01 16:26 UTC, XavierPaquet-Rapold commented on l10n/intl_en.arb
> +  "report_false_information_description": "Ad that appears to be false or misleading.",
Done

2024-06-01 16:26 UTC, XavierPaquet-Rapold commented on l10n/intl_en.arb
> +  "report_harassment_or_abuse_description": "Ad targeting a person or group in an abusive manner.",
Done

2024-06-01 16:26 UTC, XavierPaquet-Rapold commented on l10n/intl_en.arb
> +  "report_outdated_content_description": "Ad that is no longer up-to-date or relevant.",
Done

2024-06-01 16:26 UTC, XavierPaquet-Rapold commented on l10n/intl_fr.arb
> +  "news_export_success": "L'événement a été exporté avec succès",
Done

2024-06-01 18:07 UTC, MysticFragilist submitted a review, later dismissed
Le reste semble good! LGTM! :100:

2024-06-03 21:36 UTC, merged